### ISSUE TITLE
Measure chunk validation network roundtrip

### ISSUE THREAD

**Issue by pugachAG** [near/nearcore#10790]
It would be great to have a metric showing how much time it takes to distribute state witness from chunk producer (CP) to chunk validator (CV) and also deliver chunk endorsement from CV to block producer (BP).

One naive way of doing that would be include `time_sent` as part of state witness on CP side and then emit metric with time difference on CV side. For that to work we need to have clocks in sync on all nodes, which isn't the assumption we can make, especially for the nodes we don't control. 

The suggested way is to introduce a separate ack message sent from CV to CP as soon as it receive the state witness. Then CP can save `time_sent` for the state witness in memory and emit metric after receiving an ack message from CV. This way we measure CP-CV-CP roundtrip which would a reasonable approximation of real-world CP-CV-BP.

Code pointers:
* #10287 adds `ChunkStateWitnessMessage`, can be used as a guide for adding a new network message
* `chain/client/src/stateless_validation/state_witness_producer.rs`: send_chunk_state_witness_to_chunk_validators is an entry point for chunk producer
* `chain/client/src/stateless_validation/chunk_validator/mod.rs`: process_chunk_state_witness is an entry for stateless validator
* `chain/client/src/stateless_validation/shadow_validate.rs`: `shadow_validate_block_chunks` is called for every processed block to simulate stateless validation

**Comment by tayfunelmas** [comment]
Closing this as [the metric](https://github.com/near/nearcore/blob/bd80b1d2db5aa9ead143e22aa23818c9fbeed701/chain/client/src/metrics.rs#L595) is added to code and included in the [stateless validation dashboard](https://nearinc.grafana.net/d/edbl9ztm5h1q8b/stateless-validation?orgId=1). The remaining issues about missing orphan witnesses was fixed in [#10934](https://github.com/near/nearcore/pull/10934)
