### ISSUE TITLE
fix test_full_estimator

### ISSUE THREAD

**Issue by wacban** [near/nearcore#11705]
The test_full_estimator is disabled due to errors coming from the congestion control stack. Likely the congestion info is not correctly bootstrapped. Fix this issue and re-enable the test.

**Comment by wacban** [comment]
JFYI @jakmeier @nagisa

**Comment by jakmeier** [comment]
I have the fix caused by congestion control changes. We need to update the apply_state between chunks with the updated congestion info and it works again.

But I'm still working on further problems, caused by new limits that change how some estimations should work, since we can no longer fill a block with X * 1000 data receipts with a 100KB size each and expect it to finish within a single block.
