### ISSUE TITLE
Consider returning http errors for certain rpc errors

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#11792]
Currently when a rpc request is processed, we [never return a http error](https://github.com/near/nearcore/blob/6f321bdd0f2f568a90d764296469aee27a9f8208/chain/jsonrpc/src/lib.rs#L293). However, this makes it confusing to rpc operators, who may see very low "error rate" in their monitoring when there may actually be a nontrivial amount of requests that return a timeout error with a 200 response code. We may want to consider returning a `HttpError` in that function for certain rpc errors like timeout. Of course there are legitimate errors such as "account not found" that make sense to be included in a response body with a 200.

**Comment by frol** [comment]
Technically speaking, JSON RPC doesn't use HTTP status codes to indicate the result (at the very least, it is due to the fact that JSON RPC supports requests batching): https://www.jsonrpc.org/specification

@bowenwang1996 by timeout response do you refer to tx-status, broadcast-tx timeouts? They are also part of regular operations flow, aren't they?

**Comment by frol** [comment]
@bowenwang1996 FYI, changing the HTTP status codes will be a semi-breaking change. For example, non-ok response will be now handled [here in near-api-js](https://github.com/near/near-api-js/blob/88886682107fd652a113b4d60718337197e63089/packages/providers/src/fetch_json.ts#L42-L51) instead of further down the line. This means that all those legacy projects will do more retries on Timeout - one exponentionBackoff from `fetchJson` and another one from [`sendJsonRpc`](https://github.com/near/near-api-js/blob/88886682107fd652a113b4d60718337197e63089/packages/providers/src/json-rpc-provider.ts#L381-L405) (it is is calling `fetchJson`)

**Comment by bowenwang1996** [comment]
> @bowenwang1996 by timeout response do you refer to tx-status, broadcast-tx timeouts? They are also part of regular operations flow, aren't they?

I think it mostly indicates an error. This would happen either because the rpc node is falling behind, or because the network is congested. In either case it seems that an error makes sense. Do you have suggestions regarding how to distinguish between errors?
