### ISSUE TITLE
Show waiting for genesis counter

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1635]
Currently it shows number of seconds which is very unclear and doesn't change.
 We should have 00h00m00s format and update it every ten seconds.

**Comment by Rishabhraghwendra18** [comment]
Hi @ilblackdragon may you guide me in which file I have to make changes for this issue ?

**Comment by nikurt** [comment]
Not sure what this means.
If this issue is about downloading `genesis.json`, then it was fixed by downloading a compressed file: https://github.com/near/nearcore/pull/6482
If this issue is about long start up times, when `genesis.json` is huge, then it's a known issue and we are working on it , as part of making neard restarts as fast as reasonable.
