### ISSUE TITLE
Nightly tests should run with one node from stable for backward compat

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2444]
Every time we run a nightly test, we should also ensure backward compatibility (unless protocol version was updated). To do this, any time we start a cluster in nightly, we can run one node with stable version of the code.

**Comment by damons** [comment]
Moving to Phase 2. Will re-address when we get there.

**Comment by chefsale** [comment]
Currently we run all the tests with master, the concern with adding stable could cause compatibility issues. Have to have a chat with @bowenwang1996 how to approach this.

**Comment by ailisp** [comment]
Step back since no longer have time to work on this. My investigation was adding to all nightly tests require some rewrites to all nightly tests' start_cluster util function. It currently takes and start all with same binary, should be modified so it take different neard binaries run X node of one binary, and one node of another binary

**Comment by mina86** [comment]
Won’t the protocol versions mismatch when stable node tries to connect to cluster running nightly nodes?

**Comment by bowenwang1996** [comment]
Ah that is an interesting question. So originally the idea is that every commit on master should be backward compatible with the most recent stable release since we only stabilize features close to the release. However, as @matklad suggested, we should stabilize feature independently of the release, which renders this issue invalid.
