### ISSUE TITLE
Extract runtime/near-vm-runner into contract-runtime

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2815]
Now that we are adding support for more Wasm runtimes, it would be good to separate low-level details of Wasm execution into a separate folder in `nearcore`. In the long run it is going to become a standalone open source project not specific to NEAR protocol. Additionally, we might want to rename the rest of `nearcore/runtime` to `nearcore/transaction-runtime`.

For the reference: what is the difference between contract runtime and transaction runtime: https://github.com/nearprotocol/nearcore/issues/2721

Assigning to @olonho and soliciting comments from @evgenykuzyakov  and @fckt .

**Comment by olonho** [comment]
As discussed, we likely need to somewhat reconsider scope of this issue.

**Comment by bowenwang1996** [comment]
@olonho is this still relevant?

**Comment by bowenwang1996** [comment]
@matklad @olonho ?

**Comment by matklad** [comment]
I suggest closing this for now -- we do want to do something like this in the future perhaps, but it's best if this happens naturally due to better factoring of the code, etc. I don't think it makes sense to prioritize contract runtime extraction specifically -- we need first to clean up internal technical debt. 

That said -- this is totally great aspirational goal!
