### ISSUE TITLE
Prevent rocksdb corruption on running out of disk

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#2816]
Currently even though nearcore handles storage carefully and wouldnt commit only when everything succeeded. 
 Rocksdb can fail though to commit when it the node runs out of space and do that in a way that's super hard to recover (Wal file being behind the sst for example).

My suggestion we check every few seconds how much available space is there and panic when that go under 10mb for example.

**Comment by KaiserKarel** [comment]
I could have a look at this as well, if this is still a relevant issue.

I suppose we'd want the following? 

 - [ ] Start a task during initialization to poll rocksdb for available storage.
 - [ ] Use some form of signalling to shutdown the server.
 
Alternatively, would it not be better to simply check if Rocksdb has enough space before committing the transaction, and else aborting gracefully?

**Comment by bowenwang1996** [comment]
> Alternatively, would it not be better to simply check if Rocksdb has enough space before committing the transaction, and else aborting gracefully?

That sounds good to me

**Comment by KaiserKarel** [comment]
So that would basically involve adding a check to the total free memory in the data directory, on each transaction commit. Are we concerned with the performance overhead? I could also add the check every nth commit, for that it would be nice to know the median and average transaction size (on disk).

I think doing some heuristic to minimize the number of checks might be a bit premature, so I'll just check every single time first, and see what the impact is.

**Comment by bowenwang1996** [comment]
@KaiserKarel as suggested in the description of the issue, you can check it once in a while and panic if it goes under some threshold

**Comment by KaiserKarel** [comment]
Gotcha. :+1:

**Comment by KaiserKarel** [comment]
I've got an implementation working, but still deciding on how to create an appropriate test, as checking disk failure is a bit difficult to set up. Perhaps adding a sanity check where I run the containerized node with `--storage-opt size=0G`, and checking for exit 1 would suffice?

**Comment by bowenwang1996** [comment]
> I was a bit naive in thinking it would be a simple setting. Apparently --storage-opt size requires a different overlay and filesystem, so I am not sure if we can run this in CI. Alternatively, I could create a loop device, mount that and use it as data directory.

@chefsale can we potentially create a special test in CI for such scenarios?

**Comment by mikhailOK** [comment]
Several questions for how this feature is supposed to work:
1. Can we make it so that partial writes/inconsistent storage are never possible, or a heuristic is the best option? Does rocksdb have any solution built in?
2. What heuristic to use - check every X seconds, or every X transactions? How large is the average/maximum write size? Something like network might write small transactions, but GC might be larger.
3. Can something else running concurrently mess with our heuristic, such as rocksdb background compaction? Can background jobs break consistency on out of disk error?

**Comment by bowenwang1996** [comment]
@mikhailOK what else do you think we should do in addition to #4058

**Comment by matklad** [comment]
This was fixed in rocksdb itself, we took advantage of that in  https://github.com/near/nearcore/pull/7545
