### ISSUE TITLE
Expose `max_gas_burnt_view` as part of client config

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#3080]
`max_gas_burnt_view` defines the maximum burnt gas for a view call.

Since it doesn't influence the protocol (only affects RPC), it should be part of the client config instead of genesis config.

**Comment by alsakhaev** [comment]
I ran into the GasLimitExceeded error in my contract when calling the read function.

I started looking for where to change the gas limit in the node configuration. I have not found documentation for client configs anywhere. By examining the source code, it turned out that this parameter lies in the genesis (genesis.json), which is 5 GB in size. The built-in Linux text editors didn't want to work with such a large file. I discovered a HEX editor that can handle this. Replaced 200Tgas with 999Tgas.
![image](https://user-images.githubusercontent.com/15713727/117123608-ec40b100-ad9f-11eb-9de0-3ab66aca02c5.png)

Launched the client. He noticed the change by comparing the genesis hashes and cleared the entire state.
![image](https://user-images.githubusercontent.com/15713727/117123667-011d4480-ada0-11eb-9aa3-d9fa6e7bc07b.png)

Well, the synchronization of the node started from the very beginning.
![image](https://user-images.githubusercontent.com/15713727/117123689-08445280-ada0-11eb-96cf-945ab2495d18.png)

So, now it's impossible to change the gas limit for view functions.

**Comment by bowenwang1996** [comment]
> So, now it's impossible to change the gas limit for view functions.

The config you modified is in genesis and is part of the protocol, so that doesn't work. What is proposed here is to add a separate client config that does not affect the protocol to increase the limit on view calls.

**Comment by ethernian** [comment]
Yes, please fix the issue. 

It should be a no-brainer fix, max 10 lines of code to replace the source where the read-only gas limit comes from, isn't it? 
I do really not understand why the read-only gas limit is part of genesis and thus part of the consensus.

**Comment by mina86** [comment]
This isn’t yet available in a production release but if anyone wishes to test it in betanet et al with a nightly build `neard` will now accept `--max-gas-burnt-view` switch for its `init` and `run` commands. It’s also possible to add `max_gas_burnt_view` key to the `config.json` file.
