### ISSUE TITLE
function_call_cost number cannot be explained

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3094]
`function_call_cost` is currently `2319861500000` gas, see: https://github.com/nearprotocol/nearcore/blob/master/neard/res/genesis_config.json#L74

This is the major limiting factor that restricts contract call TPS to 200. Initially we thought it is so large because the fee computation accidentally adds it to it the cost of trie update, Wasm compilation and loading, receipt creation for refunds, etc. However:
* Cost of compiling 100KiB contract is `216750*100*2^10+35445963` which 100 times cheaper than the function call fee;
* Cost of creating a receipt is `108059500000` which is 21 times cheaper;
* Base cost of storage write (including trie update): `64196736000` which is 36 times cheaper.

There are no good explanations of where this cost is coming from. It might be an indication of a bug in params estimator or large sub-optimality in the runtime. We need to investigate this issue, especially since it can be an easy way to bump our TPS.

**Comment by evgenykuzyakov** [comment]
Right now when a contract code is pulled from the trie without cache we rehash it to verify the hash matches the hash given in the account structure.

In particular these 2 lines:
https://github.com/nearprotocol/nearcore/blob/9ca3117e04fc87b89e69c19916f0ed82b7a8af16/runtime/runtime/src/cache.rs#L25

and 

https://github.com/nearprotocol/nearcore/blob/9ca3117e04fc87b89e69c19916f0ed82b7a8af16/core/primitives/src/contract.rs#L10

Cost of hashing 200Kb of data according to our math estimator is `8003126` Gas per byte or `8003126 * 200000 = 1600625200000` or `1.6` Tgas on itself. That's why when a function call has an overhead of `1.6 Tgas` just for hashing the contract code if it's run on 200Kb of data.

I suggest remove hashing of the contract code completely, since hash from the account ID + trie merkalization should be enough to enforce the code hash matches the code from the Trie.

Also this `assert_eq!` is the middle of the node is rather stupid and would panic a node on corruption of the data. We're not guarded against memory corruption or trie value corruption, so data corruption should not be a problem either.

The hash should be only verified during deploy action, which is already the case.

**Comment by evgenykuzyakov** [comment]
Also it might be not hashing alone. Just reading 200Kb from the trie costs `1870335 * 200000` according to our tests 0.37 Tgas (pre safety multiplier).

**Comment by evgenykuzyakov** [comment]
I think the best way to measure cost of compilation is to run a function call block with cache on (warmed up) and a block with cache off. The difference is the cost of cold compilation.

**Comment by nearmax** [comment]
FYI singlepass is JIT, so cache helps a little bit but not much.

**Comment by evgenykuzyakov** [comment]
We also cache `preparation (e.g. gas injection) + contract code storage read`. Need to look further what takes the most amount of instructions for a base function call. Maybe allocating 64Mib of RAM for any contract call is an issue.

**Comment by bowenwang1996** [comment]
> Maybe allocating 64Mib of RAM for any contract call is an issue.

That's a lot :)

**Comment by olonho** [comment]
As mentioned in https://github.com/nearprotocol/nearcore/issues/3041#issuecomment-675407067 we *do* need proper definition of what meaning we expect from every individual fee, especially actions ones. Definition better be present in form of *probes:, inserted in proper places of the estimator code. @nearmax @evgenykuzyakov could you please cooperate here?

**Comment by bowenwang1996** [comment]
Superseded by #4401
