### ISSUE TITLE
[Discussion] Remove RPC routing from the protocol

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3148]
# Motivation
Currently RPC routing is part of the protocol. There are two issues with that:
* We reinvented routing protocol on top of RPC, which is something that already exists in multiple implementations;
* There is no reason for RPC routing to be part of the protocol, it makes it rigid and hard to change.

# Proposal

RPC routing should be implemented on top of RPC using existing routing standard on top of RPC, for example, see WAMP routing. I am sure @frol knows of other RPC routing standards too.

For the record, me, @SkidanovAlex, and @bowenwang1996 had discussion about it and agreed that we should do it at some point.

**Comment by frol** [comment]
I agree that we should limit NEAR protocol networking to the needs NEAR protocol has. RPC routing should be designed separately; I am not aware of any peer-to-peer RPC standard (haven't had a need for it before). I am not 100% sold on having routing internally and currently consider just helping the client to learn which node it should reach out for the data instead of proxying the data through a node.

**Comment by frol** [comment]
We removed RPC routing altogether in #3944. Only transaction submission involves routing now, which is part of the NEAR Protocol.
