### ISSUE TITLE
Param estimator should be run with a very large state

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3194]
It is possible that when we run param estimator most of the state is getting cached by the OS and we are not hitting SSD. We need to investigate:

*   How disk caching works in various OSs, specifically Ubuntu, since this is our target platform for validators. CC @jimmy3dita ;
*   Make sure param estimator is executed on the state that's large enough to make sure we are hitting the disk;

Note, large state is expected to slow down param estimator also because the trie gets deeper and we touch more nodes: [https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/nearprotocol/nearcore/3193](https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/nearprotocol/nearcore/3193) So if we observe and measure the slowdown, we need to make sure we deduct the effect created by the deep trie.

**Comment by olonho** [comment]
Note, that if we hit OS caches, it's not really important, as we count instructions, not wall time. What's important, is to not run from DB caches. Probably just explicitly disable those when estimating would be the best choice.

**Comment by jimmy3dita** [comment]
I'm happy to put you directly in contact with some of NEAR validators, to discuss with them these issues

**Comment by olonho** [comment]
Yeah, let's discuss it.

**Comment by matklad** [comment]
Blocked by #4771 -- need to figure that out before we can add meaningful measurements here.

**Comment by matklad** [comment]
@jakmeier we've closed #4771, do we have a next step here?

**Comment by jakmeier** [comment]
When assessing gas estimations for exact values, we have been running with `--metric time`  on large state with dropped OS page caches for a while now. I would say this addresses the issues originally raised here.

Continuous estimation is still running on non-standardised hardware (whatever buildkite assigns it). Therefore, we still rely on `--metric icount` for bot reports. It also uses a fairly small state and does not drop OS page caches. For qemu runs, this is okay.
But as we have seen that qemu is not good at estimation IO costs, therefore the absolute values from there are not to be taken as source of truth. For relative comparisons it has been okay so far. But if we want to implement parallel IO requests of any form, it qemu measurements will start to become less and less useful.

In the short term, the next step is to re-assess all estimations after the fixes to IO estimation. I have this already running and will report results here: #7519

Long term, next steps are to conclude what we want to do with IO cost estimations (#5995) and perhaps change the CE setup to use standardised hardware.

But I think we can close this issue. Feel free to reopen if you think otherwise.
