### ISSUE TITLE
Thread store into runtime for on-disk compilation

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3334]
In #3333 @olonho introduces compilation of the contract during its deployment. However, he still uses local file for storage. Instead we should be using a column in rocksdb. Unfortunately, runtime does not have direct access to the storage (only to the state). We need to thread storage into runtime. One of the options would be to pass https://github.com/nearprotocol/nearcore/blob/master/neard/src/runtime.rs#L129 into apply method here: https://github.com/nearprotocol/nearcore/blob/master/neard/src/runtime.rs#L412

**Comment by ailisp** [comment]
Implement in #3331

**Comment by nearmax** [comment]
Lets keep the scope of this issue for on-disk singleton cache only.

**Comment by nearmax** [comment]
@evgenykuzyakov @ailisp @bowenwang1996 I have discussed it with @mikhailOK and he has a valid point against Singleton:
* Compilation cache is part of the protocol and therefore it should be explicit in the semantics of the runtime methods;
* We want to avoid compiling in store crate with rocksdb into runtime because, which would make standalone runtime more complex. Also, our runtime currently enjoys benefit of having few dependencies and it would be nice to keep it this way. It is easy to make dependency inversion through interface to cut this dependency when store is an explicit argument/field, but it is going to be hard to do if it is a singleton.

**Comment by ailisp** [comment]
I think when discussed with Evgeny, we had assumption that "Compilation
cache is not part of the protocol"

> We want to avoid compiling in store crate with rocksdb into runtime
because, which would make standalone runtime more complex. Also, our
runtime currently enjoys benefit of having few dependencies and it would be
nice to keep it this way. It is easy to make dependency inversion through
interface to cut this dependency when store is an explicit argument/field,
but it is going to be hard to do if it is a singleton.

This is not the case, singleton cache only expose store, it didn't expose
rocksdb. For standalone runtime it's just store backed by InMemoryDB

**Comment by ailisp** [comment]
Hmm currently singleton store is set in create_store(rocksdb), but it
doesn't need to be rocksdb, if there's a concern to use in standalone
runtime i can made it initialize from store that's irrelevant to which
database trait is used
