### ISSUE TITLE
Consider using alternative Wasm runtimes

### ISSUE THREAD

**Issue by frol** [near/nearcore#3363]
We had some conversations here and there about wasmer 1.0 and wasmtime. The current approach is to compile Wasm down to machine code and execute that. There is an alternative approach, which is to interpret Wasm code. Given that the smart contracts are relatively small in size and already optimized, and expect to be executed in well under 1 second, I wonder if interpreting is a better strategy over compilation + execution.

[The success story of using Wasm interpreter is Rust proc-macro crates](https://github.com/dtolnay/watt), which are only used during the compilation step to get some Rust code in and produce new Rust code out. Most of the proc-macro crates require quite heavy dependencies to work with Rust AST, so it increases the compilation time compiling the proc-macros first to only execute them on a few structs in the project. Thus, the experiment [https://github.com/dtolnay/watt](https://github.com/dtolnay/watt) chose another path; they precompile the proc-macro crates into Wasm binary and release a crate with only dependency on a tiny Wasm interpreter (watt, which forked rust-wasm) and the precompiled Wasm binary in it, so the user of the crate do not need to compile the proc-macro dependencies, but instead the compile watt and execute the pre-built Wasm binary.

/cc @nearmax @olonho @willemneal

**Comment by willemneal** [comment]
I definitely think this is worth an experiment.  I wonder what the cost compares with a large binaries.  Even if they are mostly small some won't be and there might be a larger warm up cost vs the load and execution of the precompiled assembly.  Also since we have been measuring the cost of compiling contracts we would need to inject gas metering into the interpreter.

Perhaps we could have the best of both by deciding based on the size of the contract which route we take. My one concern currently is that we need to try to keep as simple as possible at this point and that seems much more complicated.

I've also been interested in adding something similar as the wasm macro used in compilation in AS.

**Comment by bowenwang1996** [comment]
@matklad @olonho what do you think?

**Comment by matklad** [comment]
TBH, one of my first questions upon joining contract-runtime was "why are we *not* using an interpreter"? Simple interpreters are generally more reliable, and starting with interpreter is forward compatible with switching to the compiler later and decreasing the costs. 

However, we already are using a compiler, use it for cost estimation of basic WASM operations, and have some CPU-intensive contracts (aurora). So I'd estimate the probability that we can switch to interpeter without increasing the costs as 0.3. Although that's non-negligible -- the gap between fast, threaded code interpreter (https://github.com/wasm3/wasm3) and a simple single-pass compiler (wasmer) shouldn't be many orders of magnitude. 

I guess, overall it's an interesting thing to experiment with, to check basic assumptions, but I don't think it's likely that we'll get something tangible out of this: even if interpreter is not slower, switching to it is risky due to unknown unknowns.

Action item here:

Run our [CPU ram soak test](https://github.com/near/nearcore/blob/c85bf403909018e24c7a83a20b9bbf33958a16c9/runtime/runtime-params-estimator/test-contract/src/lib.rs#L1031-L1042) under wasmer 0.17 and under wasm3, with and without gas metering. If get something very surprising, then look more into it.

**Comment by matklad** [comment]
>So I'd estimate the probability that we can switch to interpreter without increasing the costs as 0.3.

Oups, I realized that I was wrong! As we now know, the bulk of our execution time is gas metering. That is, we don't actually run contracts with compiled code speed today, we run them much slower. So it is feasibly to switch to an interpreter together with updating our gas metering, while still reducing the costs.

A potential benefit this can bring is faster startup times for contracts -- in theory, it should be possible to pack more "almost no-op" calls into a single block with an interpreter, as the "setup execution context" bit for interpreter might be lighter weight. 

So I've spend some time doing rough benchmarking of wasm3, a fast wasm interpreter: 

https://github.com/matklad/benchmarks/commit/888452cf422121da7864ab79e35004dd81fde279

wasm3 is only about 3x slower than wasmer when running tight wasm loop (this matches my expectations). However, it is also about 3x slower when running nop-op functions (I'ed expect it to be X times faster). That's a bit surprising to me. 

So it seems that we actually could switch to interpeter, but there isn't any wins with startup times sadly.

**Comment by bowenwang1996** [comment]
> However, it is also about 3x slower when running nop-op functions (I'ed expect it to be X times faster).

Do we know why that is the case?

**Comment by matklad** [comment]
>Do we know why that is the case?

Not really, it might be the case that there's some stupid bug in my code or in wasmer3 (turns out that the version of wasmer3 in wasmer3-rs is outdated by about ~400 commits). Might make sense to investigate further (but probably low priority)

**Comment by bowenwang1996** [comment]
@matklad is there any action item from this issue? If not let's close it

**Comment by matklad** [comment]
Let's close this: we've investigated a bunch of approaches over the years, and didn't find anything significantly better than the status quo.
