### ISSUE TITLE
[EVM] Update the EVM to the most recent version

### ISSUE THREAD

**Issue by djsatok** [near/nearcore#3506]
The implementation of the EVM in #3257 is not the most recent. Before releasing we should update the implementation

**Comment by artob** [comment]
@djsatok As discussed on the call just now, I'll take a stab at this. (Please assign the task?)

**Comment by artob** [comment]
@djsatok @mikedotexe @ailisp All right, to summarize our discussion on the sync call yesterday:

We are currently pulling in [Parity-Ethereum](https://github.com/paritytech/parity-ethereum) at revision https://github.com/openethereum/openethereum/commit/eed630a002bbebed3a3097127f2483213ff52079, dated Jun 5, 2019. That roughly corresponds to upstream's [2.6.0-beta](https://github.com/openethereum/openethereum/releases/tag/v2.6.0) release.

Since then, Parity-Ethereum has been rebranded to [OpenEthereum](https://github.com/openethereum/openethereum), and they have released the [2.7](https://github.com/openethereum/openethereum/releases/tag/v2.7.0) and [3.0](https://github.com/openethereum/openethereum/releases/tag/v3.0.0) branches. (They also note that due to database format changes, upgrading from 2.6.x to 2.7.x or 3.0 is a one-way only operation.)

Since the transitive dependency graph change for the full upgrade is rather large, and our code will need to be adjusted as well, we discussed on the call to do the upgrade in more than one step: 

1. Upgrading ASAP to the last 2.6 security release, [2.6.8](https://github.com/openethereum/openethereum/releases/tag/v2.6.8), dated Dec 31, 2019. That already rolls us forward half a year, without (hopefully) many breaking API changes.

2. Upgrading from 2.6 to the latest [3.0.1](https://github.com/openethereum/openethereum/releases/tag/v3.0.1), dated Jun 1, 2020. That'll be painful, so we should try to schedule and phase it such that it doesn't disrupt everybody's work too badly.

Since we talked, I've upgraded my local dev env progressively through 2.6.x releases. Everything still compiles perfectly up to 2.6.2, but at 2.6.3 we hit some API changes (never mind semantic versioning):

<img width="668" alt="Screen Shot 2020-10-30 at 14 58 32" src="https://user-images.githubusercontent.com/4963/97710122-02ee0e80-1ac4-11eb-8562-8a61515f854d.png">

Given that, what I'd do is send a PR right now for the no-brainer 2.6.2 update, and then work on making 2.6.3 (through 2.6.8) compile. Sound OK, @djsatok?

**Comment by djsatok** [comment]
@artob, sure, no problem, let's follow suggested approach

**Comment by artob** [comment]
> Consider run runtime/near-evm-runner/tests/standard_ops.rs test and make it pass again locally. And add a test case for blake2 precompile function

_Originally posted by @ailisp in https://github.com/near/nearcore/pull/3558#issuecomment-721907077_

**Comment by artob** [comment]
To summarize the current state of things:

1. As a first step, we upgraded to OpenEthereum [2.6.2](https://github.com/openethereum/openethereum/releases/tag/v2.6.2) in #3542. That rolled us forward about 3 months (from Jun 2019 to Aug 2019).

2. Thereafter, we upgraded to OpenEthereum [2.6.8](https://github.com/openethereum/openethereum/releases/tag/v2.6.8) in #3558. That rolled us forward another 4 months (from Aug 2019 to Dec 2019), and brought us to parity with the [Istanbul](https://eth.wiki/en/roadmap/istanbul) hard fork. The upgrade chiefly required implementing a new API that is called when the new `CHAINID` opcode is executed.

3. I'm currently working on the upgrade to OpenEthereum [2.7.2](https://github.com/openethereum/openethereum/releases/tag/v2.7.2). That will roll us forward another 2 months (from Dec 2019 to Feb 2020). And that will get us to a stable release: the whole 2.6.x series is considered beta, with 2.7.x being the stable branch. To complete the upgrade, there are a number of dependency issues and build errors to address:

<img width="861" alt="Screen Shot 2020-11-06 at 16 11 54" src="https://user-images.githubusercontent.com/4963/98376435-2416a800-204c-11eb-97b4-60f8232d4f52.png">

<img width="862" alt="Screen Shot 2020-11-06 at 16 12 21" src="https://user-images.githubusercontent.com/4963/98376451-2da01000-204c-11eb-87df-0421a288010a.png">

4. As a final step, we are planning to upgrade to OpenEthereum [3.0.1](https://github.com/openethereum/openethereum/releases/tag/v3.0.1), the current stable release at the time of writing. That will roll us forward another 4 months (from Feb 2020 to Jun 2020), for a total of 12 months forward from the starting point.

**Comment by artob** [comment]
Related to this issue, here’s a Solidity/EVM version cross reference that I compiled at @djsatok's request:

https://gist.github.com/artob/c2b5dc6c834134f3e7c1ef86232b416d

**Comment by artob** [comment]
Related to this issue, here’s a Solidity/OpenEthereum version cross reference that I compiled at @djsatok's request:

https://gist.github.com/artob/c2b5dc6c834134f3e7c1ef86232b416d

**Comment by artob** [comment]
As [discussed](https://www.youtube.com/watch?v=JFiwTLnNclU&t=875) on the [weekly call](https://github.com/near/nearcore/discussions/3613) today, the current state of this task is that we've now completed and merged the 2.7.2 upgrade (#3595), and it makes sense to freeze the dependency at that release for now.

OpenEthereum [surprised](https://twitter.com/ilblackdragon/status/1325860605123686400) us a week ago by releasing [3.1.0](https://github.com/openethereum/openethereum/releases/tag/v3.1.0) which they had been developing in [another repository](https://twitter.com/ilblackdragon/status/1324794739267411973). OpenEthereum 3.1.0 _isn't_ a continuation of the 3.0.x lineage, but rather [a fresh fork of the old 2.5.x branch](https://medium.com/openethereum/vision-for-openethereum-ex-parity-client-eb7b11f6eef8).

In investigating the new branch this week, my assessment, and the team's consensus, is that upgrading to OpenEthereum 3.1.0 is too risky right now, so we will build on 2.7.2 for the time being.

The 2.7.2 version was the last Parity Ethereum release, before the OpenEthereum team took over. So, it is relatively popular and well tested. It will serve us as a “good enough” release until the Berlin hard fork takes effect, which may require an upgrade to 3.1.x, or else some backporting work to 2.7.x.

@djsatok @evgenykuzyakov I think we can close this task, for now, as I don't think there's anything further actionable here until it's time to prep for the Berlin hard fork (in January, perhaps, if Berlin doesn't get delayed further).

**Comment by djsatok** [comment]
Closed by #3595 and previous PRs
