### ISSUE TITLE
CI may be broken

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3587]
When running tests without nightly features, we should not compile tests with all features, which will cause `no_cache` to be enabled and mess up the results. Currently `test_data_reset_before_state_sync` does not pass locally but passes on CI.

**Comment by chefsale** [comment]
So, tthat shouldn't be the case, the tests running running nightly are compile with nighlty features and standard tests are without. For example this code: https://github.com/near/nearcore/blob/master/scripts/parallel_run_tests.py#L28. And every run runs on an isolated machine so there is no build cache. 

I think that is possibly on your side, that you maybe compiled the binary with one set of flags and run the tests with other, maybe cargo is using the old cached build from before? Can you make sure you do a clean build for both to verify that is the case. Run tests for one, clean and than for the others?

**Comment by bowenwang1996** [comment]
Did cargo clean and rerun and it gave the same result. @mikhailOK also confirmed this.

**Comment by chefsale** [comment]
How did you run the tests that would be helpful, as well.

**Comment by mikhailOK** [comment]
`test_data_reset_before_state_sync` did not pass because of a bug that was fixed in #3593
It did pass with `no_cache` feature enabled, which seems to be the reason CI didn't catch the bug.

`no_cache` feature is evil, we should consider running CI without it or getting rid of it

**Comment by chefsale** [comment]
We dont use no_cache and that wasnt the issue, the problem was that we were not using cargo directly but had a seperate script parallel_tun_test which tried to run tests in seperate docker containers due to legacy port conflist in integration tests, whuch are mostly moved to nayduck now and it happens that the script was broken and wasnt working as expected and that caused test flakiness. I have removed it and just use cargo now instead.
