### ISSUE TITLE
bug: Param estimator reuses accounts that rely on the storage

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#3601]
Param estimator reuses accounts for measuring different host function gas numbers.
Some of these arguments depend on the existing storage. If we use an account, then the 2nd estimate run on this account will hit a modified storage and may receive a different result.

For example `storage_remove_10b_key_10kib_value_1k` has only 1 account with keys (for some reason). It requires the existing values in the trie to be able to count the number of bytes removed. It causes the cost to either overestimate or underestimate.

**Comment by ailisp** [comment]
I think i finally understand this bug:

>    For example storage_remove_10b_key_10kib_value_1k
     has only 1 account with keys (for some reason). It requires the
    existing values in the trie to be able to count the number of bytes
    removed. It causes the cost to either overestimate or underestimate.

it's because the key added is by the previous storage_write_10kib_key_10b_value_1k test, which is random select block_size*iter_block accounts from total accounts-num accountsThen, storage_remove_10b_key_10kib_value_1k is randomly select block_size*iter_block accounts from total accounts-num accounts, and they (most likely) have no keys at all.

A fix should be, before test like `storage_remove_10b_key_10kib_value_1k` (there's several similar storage_remove tests), either
- add storage key,value to all accounts instead of random selected accounts
- in `storage_remove_10b_key_10kib_value_1k` reuse exact same accounts in `storage_write_10kib_key_10b_value_1k` instead of currently we randomly select from total account-num accounts again.
