### ISSUE TITLE
Memory leak in telemetry connections

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3767]
According to @pmnoxx, we try to open a connection to the telemetry endpoint every 10s and this caused some memory leaks.

**Comment by frol** [comment]
Oh cool... I guess, it is time to try to update actix and actix-web.

**Comment by bowenwang1996** [comment]
@frol do you want to do it?

**Comment by frol** [comment]
Yes, I will give it a try after I finish with #3177

**Comment by pmnoxx** [comment]
@frol I'll provide you later details of the leak, it should help you get started

**Comment by bowenwang1996** [comment]
@pmnoxx @frol I think we recently did some updates to the telemetry connections. Is this still an issue?

**Comment by frol** [comment]
I have never observed it myself. I don't feel this should be kept open, since it did not cause any measurable issues, and we can re-open it once we get back to investigating memory leaks and re-consider if we want to fix it now. This is a pragmatic approach, but I feel that old open issues with a clear action item should be closed so we can focus on the pressing items.
