### ISSUE TITLE
Remove CORS logic from neard

### ISSUE THREAD

**Issue by mhalambek** [near/nearcore#3947]
All CORS logic can be handled by setting up reverse proxy and setting CORS response headers, there is no need to implement
this inside neard when better and tested out solutions exist.

This is related to having a bug which disabled all remote access due to the bug introduced in neard.

**Comment by frol** [comment]
Reverse-proxy is free to set its own CORS rules. JSON RPC server allows everyone to access the service which is absolutely fine for the type of service, and I don't think we need to bother with extra configuration of all the reverse-proxies and adding extra documentation on how to run RPC node behind reverse proxy just to set CORS `*`.

The issue in question was due to the breaking change in the library and this CORS default suddenly became more restrictive than we want.
