### ISSUE TITLE
DB migration 17 -> 18 is too disruptive

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4054]
17 -> 18 migration requires going through all of the headers in storage. Since currently we do not garbage collect headers, on mainnet for example there are more than 20 million headers and this migration is expected to take hours to finish. In addition, every node has to apply this migration and it may cause a major disruption to the network. We should consider alternative options, such as populating `ColHeaderHashesByHeight` lazily or not introducing this column until we garbage collect headers.

**Comment by Kouprin** [comment]
`ColHeaderHashesByHeight` is GCed and limited by `chunk_tail`, so it don't store all Headers. I guess the issue is in using `map_col` that rewrites all Headers.

I suggest the following fix: avoid using `map_col` and iterate through all Headers with no rewriting them. @bowenwang1996 How to test how much time it will take after the fix is added easily?

**Comment by bowenwang1996** [comment]
> How to measure easily how much time it will take after the fix is added?

You can try spin up a mainnet node with existing data, which can be found [here](https://near-protocol-public.s3.ca-central-1.amazonaws.com/backups/mainnet/rpc/data.tar)
