### ISSUE TITLE
Near sync stopped at 31938650

### ISSUE THREAD

**Issue by lcgogo** [near/nearcore#4087]
**Describe the bug**
My near 1.17.0 node is stopped sync at 31938650
After update to 1.18.0, the logs is still the same.

logs is like below

Mar 12 11:04:12.920  WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
Mar 12 11:04:13.140  INFO stats: #31938650 Downloading blocks 99.98% (3327)  21/18/40 peers ⬇ 582.2kiB/s ⬆ 1.0MiB/s 0.00 bps 0 gas/s CPU: 397%, Mem: 2.3 GiB

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

near 1.17.0

**Additional context**

**Comment by bowenwang1996** [comment]
Well version 1.17.0 is not compatible with the latest version because there is a protocol upgrade. The reason why it does not work after you update it later is because your node already applied the old state transition on the first block of the new epoch that is on the new protocol version and therefore your state has already diverged. In this case you need to either recover from a backup or resync your node.

**Comment by lcgogo** [comment]
> Well version 1.17.0 is not compatible with the latest version because there is a protocol upgrade. The reason why it does not work after you update it later is because your node already applied the old state transition on the first block of the new epoch that is on the new protocol version and therefore your state has already diverged. In this case you need to either recover from a backup or resync your node.

OK, please figure out this in the release note if the upgrade is not compatible with the old version.

**Comment by bowenwang1996** [comment]
> give the block height for the hard fork height.

This is not possible to know in advance because of how our upgrade process works. When 80% of validators upgrade, the protocol will upgrade and therefore it is impossible to predict when that actually happens beforehand. However, we have implemented a feature that will make the node automatically shut down if it detects that the protocol version is about to change and it is still on the old version.
