### ISSUE TITLE
Problem running neard with nightly_features

### ISSUE THREAD

**Issue by EgorKulikov** [near/nearcore#4294]
**Describe the bug**
If you build current master with --features "nightly_protocol nightly_protocol_features" and then run node on mainnet it panics:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: ``93on1kcuqTXU94zGyGvBm3YYpPqCkaM8bssbxndgbeRX``,
 right: ``DuSTmwKKf6es6h5couuf5ds46kSSxm6jCbUUDgWzjxmD``: Storage already exists, but has a different genesis', neard/src/runtime/mod.rs:269:13

**Comment by bowenwang1996** [comment]
@posvyatokum could you potentially take a look at this?

**Comment by posvyatokum** [comment]
@EgorKulikov It seems like this migration https://github.com/near/nearcore/blob/master/neard/src/lib.rs#L208
wasn't applied. Maybe you previously run neard with nightly features before this commit https://github.com/near/nearcore/commit/61c252912bdf6a4128c7947f0b7e26af10c4c97d? So your storage version is 1000 and your local genesis json hash is calculated with the old function.
I don't know use cases for running neard with nightly features, I assumed one would not reuse storage because of the combination of this https://github.com/near/nearcore/blob/master/neard/src/lib.rs#L225 and this https://github.com/near/nearcore/blob/master/neard/src/lib.rs#L76

**Comment by bowenwang1996** [comment]
@EgorKulikov does this still happen?

**Comment by EgorKulikov** [comment]
I think Polina was right about the cause, so this can be closed
