### ISSUE TITLE
Optimize delayed local receipts tracking in Indexer Framework

### ISSUE THREAD

**Issue by frol** [near/nearcore#4317]
In #4316, we hot-fixed fetching local receipts that were delayed due to network congestion, but it would be ideal to track delayed local receipts in intermediate in-memory storage (hashmap), so we don't need to rebuild the whole streamer message for the previous blocks just to look up for a single local receipt.

Obviously, if we start from the block that already has an execution outcome for a delayed local receipt (and the list of tracked local receipts that are delayed is still empty), we can fall back to this current implementation.

# Context

Local receipts are not stored in the storage (e.g. `EXPERIMENTAL_receipts` method cannot provide any information about them)

**Comment by khorolets** [comment]
For the history, we've met weird situation while running indexer-for-explorer from genesis to handle https://github.com/near/near-indexer-for-explorer/issues/74

`30518869` caused the indexer to slow down drastically. After investigation we found out that non-optimized delayed local receipt tracking logic caused that. I've made a fix https://github.com/near/nearcore/commit/91e228077bf00933c8ce20de861ddc544f7014f0

The fix was applied to my custom indexer build which is running to handle the issue I've mentioned in the beginning. Later I'll prepare a PR to address this issue.
