### ISSUE TITLE
Store restored recepts in the storage

### ISSUE THREAD

**Issue by frol** [near/nearcore#4337]
#4248 implemented a protocol upgrade that restores receipts in the first block of an epoch when the protocol will become effective, but the current implementation only cared about the state consistency while we also want to maintain storage consistency for JSON RPC and Indexer clients. By storage consistency, I mean that we used to be able to query all the non-local receipts from the storage ([view-client](https://github.com/near/nearcore/blob/928f15df25ca4128d88b98e930d580ed2023d576/chain/client/src/view_client.rs#L879-L890)).

After brief sync with @bowenwang1996 we came to conclusion that it is possible to implement this support as a part of the protocol change and keep all the layers built on top happy.

**Comment by bowenwang1996** [comment]
To be specific, we only need to store those receipts to `ColReceipts`. Execution outcomes will be populated once we apply those receipts.

**Comment by bowenwang1996** [comment]
@Longarithm what is the status of this issue?

**Comment by Longarithm** [comment]
@bowenwang1996 I didn't start it yet, while working on precompilation. Will start today

**Comment by Longarithm** [comment]
@bowenwang1996 I think this is the best place to add restored receipts: https://github.com/near/nearcore/blob/7330f37380057e45e02cac9dc4a04c72e4338242/chain/client/src/client.rs#L561
These outgoing receipts are saved into `EncodedShardChunk` which is passed to `distribute_encoded_chunk` and then to `decode_and_persist_encoded_chunk` where the chunk itself is saved into `store_update`.
The issue is that `Client` doesn't know `NightshadeRuntime`, where `migration_data` is stored. In the past we decided to avoid extending `RuntimeAdapter` with method `get_migration_data`, but now I don't see a better option. What do you think?

**Comment by bowenwang1996** [comment]
@Longarithm what is the issue with saving them to database when we load them the first time?

**Comment by Longarithm** [comment]
@bowenwang1996 oh, that would be simpler. Then adding field like `restored_receipts` to `ApplyTransactionResult` should work.
