### ISSUE TITLE
Migration to introduce metadata in execution outcome fails

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4450]
Migration introduced in #4376 fails:
```
thread 'main' panicked at 'BorshDeserialize should not fail: Custom { kind: InvalidInput, error: "Unexpected variant index: 125" }', core/store/src/migrations.rs:846:14
```

To reproduce, remove the 22 -> 23 migration and apply this migration directly on top of archival data for mainnet. Feel free to sync with @chefsale on how to get the archival data for mainnet.

**Comment by ailisp** [comment]
@bowenwang1996 my network is very unstable today, just have 1.3T mainnet state downloaded on a instance, almost unable to finish typing one command before ssh stucked. Will try next Monday

**Comment by ailisp** [comment]
@bowenwang1996 Looks like the error is from an invalid ExecutionOutcome stored in mainnet. I'm not sure how to handle it, maybe **simply drop it** given it cannot be borsh deserialized with current definition of ExecutionOutcomeWithIdAndProof so it's junk?

Here is the problematic `Vec<ExecutionOutcomeWithIdAndProof>` by dumped by std::fs::write: 

https://github.com/ailisp/migration-fail-repro/blob/master/h6QEnvsiX5HcgEqKt5PNLKkm4ztZHM9BxYFmEhw6pxf

Not sure how many of these ExecutionOutcomes are corrupted. Guess it's not many because run for more than 20 minutes, got 1.5M execution outcomes, this is the first fail.

**Comment by bowenwang1996** [comment]
@ailisp one way to fix it is to re-apply the block that generates the execution outcome. Please sync with @khorolets on how to address this so that indexer is not affected by the migration.

**Comment by ailisp** [comment]
@khorolets in short, some execution outcomes were not migrated properly after a (still unknown) history migration and those execution outcomes cannot be borsh deserialized. I'm going to change these execution outcomes, and let you know which are them, and I think you can do a manually update on these execution outcomes on indexer side. Do you have a better plan?

**Comment by khorolets** [comment]
> @khorolets in short, some execution outcomes were not migrated properly after a (still unknown) history migration and those execution outcomes cannot be borsh deserialized. I'm going to change these execution outcomes, and let you know which are them, and I think you can do a manually update on these execution outcomes on indexer side. Do you have a better plan?

Sounds legit, thank you!

**Comment by bowenwang1996** [comment]
I believe this is already fixed
