### ISSUE TITLE
`broadcast_tx_commit` behavior changed between 1.19.2 and 1.20.0-rc.1

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4464]
The latest release broke `backward_compatible.py` because the behavior of `broadcast_tx_commit` changed. More specifically, https://github.com/near/nearcore/blob/b7c8a3b5d2bfaeb1d689972fd867d1c10afcc440/pytest/tests/sanity/backward_compatible.py#L110 used to work if the stable node runs 1.19.0 but the assertion fails with 1.20.0-rc.1. What happened is that the test is not well written and the promise actually fails. However, since the promise is not the return result of the function call, the execution is considered successful, but it appears that something changed with 1.20.0-rc.1 and the rpc response becomes
```
AssertionError: {'jsonrpc': '2.0', 'error': {'name': 'HANDLER_ERROR', 'cause': {'name': 'TIMEOUT_ERROR'}, 'code': -32000, 'message':
'Server error', 'data': 'Timeout'}, 'id': 'dontcare'}
```
instead.

To reproduce, change [`branch`](https://github.com/near/nearcore/blob/b7c8a3b5d2bfaeb1d689972fd867d1c10afcc440/pytest/tests/sanity/backward_compatible.py#L28) between `1.20.0` and `1.19.2` to see the difference.

**Comment by bowenwang1996** [comment]
@frol @khorolets please take a look at this issue. We need to figure out what happened before making the mainnet release

**Comment by khorolets** [comment]
@bowenwang1996 share please a trick how to switch between branches. My attempts to run it from 1.19.2 always switch me to 1.20.0 :(

**Comment by bowenwang1996** [comment]
> My attempts to run it from 1.19.2 always switch me to 1.20.0 :(

Change the line to `branch = "1.19.2"`

**Comment by frol** [comment]
I extended `state-viewer` with a command to dump all the data from `ColReceipts` "table", and it turned out that there is only a single refund receipt stored on the "current" node. After further investigation I learned the genesis file generated by the `neard testnet` command is different: 1.19.2 produces the one with:

```json
"num_block_producer_seats_per_shard": [2],
"avg_hidden_validator_seats_per_shard": [0],
```

while 1.20.0 produces:

```json
"num_block_producer_seats_per_shard": [1, 1, 1, 1],
"avg_hidden_validator_seats_per_shard": [0, 0, 0, 0],
```

Once I patched the test to use the genesis file with the values from 1.19.2 release, the backwards compatibility tests passes.

Thus, I am still not sure what caused the change, but I confirm that the test is fine and we don't seem to need to do any further work right now. I am not sure if we want to revert the behavior of `testnet` (localnet), though, since I don't use it myself.

cc @bowenwang1996 @khorolets
