### ISSUE TITLE
Consider adding a way to account for IO-costs without qemu

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4566]
At the moment, we account for IO-costs (the number of bytes transfered to/from kernel via `read*`, `write*` family of syscalls) only in the qemu:

[https://github.com/near/nearcore/blob/84ae110d99d26a5638d4aaca2ddaf08d048e0920/runtime/runtime-params-estimator/emu-cost/counter_plugin/counter.c#L104-L124](https://github.com/near/nearcore/blob/84ae110d99d26a5638d4aaca2ddaf08d048e0920/runtime/runtime-params-estimator/emu-cost/counter_plugin/counter.c#L104-L124)

We do this by intercepting the syscalls.

One alternative is to, instead, override the corresponding `libc` functions. For example (from [this post](https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html#practical-applications)), the following injects delay into the poll function:

<pre>#<span class="error">[no_mangle]</span>
 pub extern "C" fn poll(
 _fds: *const u8,
 _nfds: usize,
 _timeout: i32,
 ) -> u32 {
 sleep_ms(500);
 1
 }</pre>

Note that this doesn't do proper forwarding – for that, I think we'd need `dlopen` libc directly.

There are two benefits in adding this kind of IO-conting;

*   first, we can cross check that qemu results are reasonable
*   second, we can get IO-cost estimation without qemu, which improves debugging workflows.

**Comment by matklad** [comment]
@jakmeier I think you are a proponent of just using wall-clock time for storage costs. Do you think we should just close it? Do you think it's worth it to remove io-tracking from quemu altogether?

**Comment by jakmeier** [comment]
Yeah I think ultimately, we want to have wall-clock timing for storage costs. That's gives most accurate results in my opinion.

But we still want a way to roughly estimate costs. Qemu based estimations aren't  all that great. The suggestion in this issue is probably better. But I am already half-way done with an alternative. I filed #7440 to track progress on that.

I wouldn't touch the qemu estimation for now, let's first get the predecessor done and then it will be clearer what we still want to keep around. Ideally, we can get rid of qemu entirely.

I will close this issue for now, as there is currently no plan to pursue it further. We can reopen it if the plan changes.
