### ISSUE TITLE
near-network production and test code separation

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#4893]
I noticed that production and test code are not properly separated in `near-network`.

Currently `integration-test/network/*.rs` uses functions to production code, that are not called by production code. In addition there are data structures, code paths that add `ping` information to `PeerManager`, however this is used only for test purpose.
This has a few issues:
- such structure can potentially infinitely grow in memory usage
- running test code in production, could potentially cause crashes, if code is not written properly
- doing code analysis, test coverage is more complicated, as you have to analyze also test code.
-  There are test methods, that could be too slow if run in production, they are used by tests, but someday someone could rewrite code, and potentially call them causing node to become unresponsive.
- This will also allow me to migrate some python tests, and run them in CI. In addition, this will make writing future tests for network much easier.

My proposal is to move hide `integration-test/network/*.rs`  behind `adversarial` flag, and all code test code it calls in `PeerManager` as well.

Btw, `#[cfg(test)]` only works for methods within the same crate, so it can't be used here.

In order to do this we would have to start running CI with `cargo --features adversarial`.

This is following discussion at https://github.com/near/nearcore/pull/4820

Edit:
I checked the tests methods, which in `PeerManager` are not executed in production, the structure should be empty. However, I still think it's a good idea to separate them. 

Edit 2:
This issue blocks me from merging https://github.com/near/nearcore/pull/4820, because new test depends on `adversarial` functionality. I would rather not have that test code enabled by default.

**Comment by pmnoxx** [comment]
Here is another reason, why we want to compile build with --adversarial in CI:
http://nayduck.near.org/#/build/2184

```+ cd /datadrive/nearcore
+ git remote update -p
From https://github.com/nearprotocol/nearcore
 - [deleted]           (none)     -> origin/remove-act
   6e8fb9b5..6fef2890  catchup-blocks-parallel -> origin/catchup-blocks-parallel
   423e637e..c0112b2f  master                  -> origin/master
+ git checkout -f c0112b2fc57f0dd1c1ec8c77ddb3ddd5b1c0c222
Previous HEAD position was 6e8fb9b5 Merge branch 'master' into catchup-blocks-parallel
HEAD is now at c0112b2f refactor: remove ActualRuntimeConfig (#4890)
+ cargo build -pneard --bin neard --features adversarial
   Compiling near-primitives v0.1.0 (/datadrive/nearcore/core/primitives)
   Compiling near-chain-configs v0.1.0 (/datadrive/nearcore/core/chain-configs)
   Compiling near-chain-primitives v0.1.0 (/datadrive/nearcore/chain/chain-primitives)
   Compiling near-store v2.2.0 (/datadrive/nearcore/core/store)
   Compiling near-network-primitives v0.1.0 (/datadrive/nearcore/chain/network-primitives)
   Compiling near-pool v0.1.0 (/datadrive/nearcore/chain/pool)
   Compiling near-vm-logic v3.0.0 (/datadrive/nearcore/runtime/near-vm-logic)
   Compiling near-chunks-primitives v0.1.0 (/datadrive/nearcore/chain/chunks-primitives)
   Compiling near-vm-runner v3.0.0 (/datadrive/nearcore/runtime/near-vm-runner)
   Compiling near-client-primitives v0.1.0 (/datadrive/nearcore/chain/client-primitives)
   Compiling near-network v0.1.0 (/datadrive/nearcore/chain/network)
   Compiling near-chain v0.1.0 (/datadrive/nearcore/chain/chain)
   Compiling node-runtime v3.0.0 (/datadrive/nearcore/runtime/runtime)
   Compiling near-jsonrpc-primitives v0.2.0 (/datadrive/nearcore/chain/jsonrpc-primitives)
   Compiling near-chunks v0.1.0 (/datadrive/nearcore/chain/chunks)
   Compiling near-epoch-manager v0.0.1 (/datadrive/nearcore/chain/epoch_manager)
   Compiling near-client v0.1.0 (/datadrive/nearcore/chain/client)
   Compiling near-jsonrpc-client v0.1.0 (/datadrive/nearcore/chain/jsonrpc/client)
error[E0004]: non-exhaustive patterns: `&IbfMessage { .. }` not covered
   --> chain/client/src/test_utils.rs:575:27
    |
575 |                     match msg {
    |                           ^^^ pattern `&IbfMessage { .. }` not covered
    | 
   ::: /datadrive/nearcore/chain/network/src/types.rs:658:5
    |
658 |     IbfMessage {
    |     ---------- not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `&NetworkRequests`

For more information about this error, try `rustc --explain E0004`.
error: could not compile `near-client` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
# command finished with exit code 101 after 25 seconds```

**Comment by pmnoxx** [comment]
Here is the related PR: https://github.com/near/nearcore/pull/4894

**Comment by pmnoxx** [comment]
@bowenwang1996 @mina86 @matklad @frol  What do you think?

**Comment by bowenwang1996** [comment]
Sounds good to me. Given the use case, we probably want to rename `adversarial` as well

**Comment by pmnoxx** [comment]
How about renaming `adversarial` to `test_features`?

**Comment by bowenwang1996** [comment]
Yeah that sounds reasonable

**Comment by frol** [comment]
I absolutely would love to see a better separation all the way through nearcore, so if you can make some steps towards it, go for it!

**Comment by mina86** [comment]
My one worry is that I would still want to see `cargo test` run without adversarial feature since that’s what is running in production. If we only do `cargo test --feature adversarial` (or `cargo test --feature test_features`) in CI we don’t actually test what ends up running. At the same time, the time it takes for pre-commit checks is already infuriating (especially as we need to wait for buildkite to finish after updating branch) so doing `cargo test` and `cargo test --feature adversarial` in buildkite might get even more annoying.

PS. The particular build failure could be tested with `cargo check`.

**Comment by matklad** [comment]
Thoughts: 

* I don't think hiding additional test functions is really beneficial
* Hiding extra test logic is obviously required. Here we have a choice between runtime checks and compile-time checks. I slightly favor runtime checks here, as compile-time features increase accidental complexity substantionall.
* For data structures, we *could* do runtime-checks as well, but that's going to add non-trivial overhead anyway -- while an extra always not-taken if in code doesn't matter, an extra field in frequently used data strcutrute does matter.

Given that we need extra fields here, hiding them behind cfg and adding an extra CI job seems a reasonable solution. Code wise though, I would try to minimize the amount of feature checks we need to do all other the place. Rather than doing this:

```rust
pub struct PeerManagerActor {
    ...
    #[cfg(feature = "adversarial")]
    adv_disable_edge_propagation: bool,
    #[cfg(feature = "adversarial")]
    adv_disable_edge_signature_verification: bool,
    #[cfg(feature = "adversarial")]
    adv_disable_edge_pruning: bool,
}

...

#[cfg(feature = "adversarial")]
let cond = act.edge_verifier_requests_in_progress == 0
    && !act.adv_disable_edge_pruning;
#[cfg(not(feature = "adversarial"))]
let cond = act.edge_verifier_requests_in_progress == 0;
```

Consider centralizing the checks like this:

```rust
pub struct PeerManagerActor {
    ...
    adv: Adv
}

let cond = act.edge_verifier_requests_in_progress == 0
    && !act.adv_disable_edge_pruning();

#[cfg(feature = "adversarial")]
struct Adv {
    disable_edge_propagation: bool,
    disable_edge_signature_verification: bool,
    disable_edge_pruning: bool,
}

#[cfg(not(feature = "adversarial"))]
struct Adv {
    disable_edge_propagation: bool,
    disable_edge_signature_verification: bool,
    disable_edge_pruning: bool,
}

impl Adv {
  #[cfg(feature = "adversarial")]
  fn disable_edge_pruning(&self) -> bool { self.disable_edge_pruning }
  #[cfg(not(feature = "adversarial"))]
  fn disable_edge_pruning(&self) -> bool { false }
}
```

The problem with `#[cfg()]` checks sprinkled throughout the code is that you'd have to run `cargo check` twice to get all the errors, and you might get some spurious unuseds that way. 

All that being said, I fully agree with mina86 that our CI is already unreasonably bulky, and that adding an extra row to our testing matrix doesn't make the situation better. So, I strongly suggest thinking about the ways we can test functionality without adding test-only code. There are also to philosophical reasons for that: 

* if we need some extra knobs or visibility in tests, we might want to need them in production. Like, if we are using `Ping` messages to test if the things get through, than maybe we need an ability to check this in prod as well? The messages might not be delivered due to a faulty network, and we'd love to see that. So perhaps we need some logging calls somewhere to expose this info? And, if we have logging calls, we can use them in tests to check that messages are delivered or dropped? 
* it'd be great to actually test the code we ship, rather than the code modified for testing purposes.


To some up: I don't hate it, but I do feel that doing more of `#[cfg(is-this-testing-code)]` makes the code harder to maintain. It would be great if we can find some other way around this problem, but, if that's impossible, adding an extra CI pipiline feels reasonable.

**Comment by pmnoxx** [comment]
@matklad I agree, ideally I would prefer to write tests, which don't touch production code at all, and test full code functionality as it is.

There are a few approaches we can take:
1) mocking
We discussed this approach before, but decided not to go through that route. 

Although, it's possible to mock other actors, structures, this makes all tests really rigid. Even small changes in code, like refactoring, may break tests, and require to spend hours on having to redo mocking tests. 

2) integration tests
Although it's possible to write integration tests without modifying any code. Sometimes it's tricky to write tests that verify whenever nodes are in correct state. 

To make it easier to write tests, we added the following
- Rpcs to retrieve state from nodes. This test code should be safe to execute, as it's a code that reads the state. However, it's probably best not to enable it by default in production for now. However, we could enable it for debugging in the future.
- Rpc to change constants, timeouts, etc. By default, those functions should have no effect, unless they are needed for specific tests. It's often useful to change timeouts, in order to avoid waiting a few minutes, hours to test specific behavior of the node. It general it should be safe to have this code compiled in production, because extra logic should have no effect unless though methods get called. 
- New type of messages `Ping`, `Pong` to test routing. It's much easier to test routing separately from rest of the logic, like delivery of `Chunks`, etc.

I think using either `#[cfg(feature="test_utils")]` or having having a boolean like `is_test` inside `PeerManager` is doable.
However, if we don't use `test_utils` feature, it's possible to have some code left enabled in production, which was not intentional. `Ping`/`Pong` messages will work in production, even though the only way to initialize `Ping` is by having a modified client, so this is clearly not intentional. 


Although, I see your point. Rather than having this:
```
            #[cfg(not(feature = "test_features"))]
            let condition = true;
            #[cfg(feature = "test_features")]
            let condition = !self.adv_disable_edge_propagation;
            if condition {
                 ...
            }
```
I would prefer rather to see:
```
            if !self.adv.disable_edge_propagation.unwrap_or(false) {
                 ...
            }
```

**Comment by mina86** [comment]
Ping sounds makes perfect sense to include in production actually.  Similarly an RPC to dump routing table state.  They both could be useful in debugging.  We might want to limit who is authorised to issue those RPCs, e.g. accept them only when done from localhost or some smarter authentication method.

**Comment by pmnoxx** [comment]
@matklad I added "struct Adv" as you suggested inside https://github.com/pulls

**Comment by pmnoxx** [comment]
I'll mark this PR as closed. We made `cargo test` run with `test_features`, and e added `Adv`.
