### ISSUE TITLE
Add CI check for protocol version increase

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4956]
In the implementation of certain protocol features, we rely on the fact that no protocol version is skipped. As a result, if we increase protocol version by more than 1 in one release, it could lead to bugs. We should add a CI check for this.

**Comment by mina86** [comment]
There’s still a corner case which this test won’t catch:
1. Cut a 1.42.0 release with protocol version 24.
2. Increase protocol version on master branch to version 25. This works because the test will compare against 1.42 binary.
3. Cut a 1.43.0-rc1 release with protocol version 25.
4. Increase protocol version on master branch to version 26. This works because the test will compare against 1.43-0-rc1 binary.
5. Cut a 1.43.0-rc2 release with protocol version 26.
6. Cut a 1.43.0 release with protocol version 26 which is two higher than previous stable release.

**Comment by mzhangmzz** [comment]
Isn't this covered by the upgradable test? If we increase protocol version by more than 1 from the last stable release and some features will break because of that, the upgradeable test will not pass right?

**Comment by mina86** [comment]
I’d imagine you’re not guaranteed to hit the scenario in which the test breaks.
