### ISSUE TITLE
Create integrated test that checks that costs don't change by accident

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4961]
In [https://github.com/near/nearcore/pull/4959](https://github.com/near/nearcore/pull/4959), I am having trouble coming up with a test that checks that configuration upgrade is done correctly. Ie, what if I accidentally change some _other_ cost during copy-paste of the config, how do I protect against it? I think what we need to do is the following:

Add an integrated test, which runs a specific function in the test contract using the latest runtime config, and asserts that Gas Profile we get in the end matches our expectations (we probably need two sets of expectations for stable and nightly protocol).

We can use `test-contract-rs` as our test contract, but we need to add an `fn sanity_check()` function to it, which calls every possible host function. (so, we also should assert that the profile doesn't have blank spots).

Given such test, we can easily check that configuration changes lead to intended outcomes (only relevant costs go lower), without _specifically_ paying attention to it. IE, if some costs change accidentally for whatever reason, such test will caught this bbug.

**Comment by bowenwang1996** [comment]
@matklad I retagged it as T-contract-runtime since this requires more domain specific knowledge of the contract runtime

**Comment by mooori** [comment]
@nagisa (assignee) would you mind if I work on this issue?

**Comment by nagisa** [comment]
Feel free to grab this!

**Comment by mooori** [comment]
Does the following approach make sense?

1. Setup a new module for the test: `integrations-tests/src/tests/runtime/sanity_checks.rs`
2. Load `RuntimeConfig` from `RuntimeConfigStore`. Do this since `PROTOCOL_VERSION` depends on whether feature `nightly_protocol` is set.
3. Start a node and deploy the test contract, similar to [`setup_test_contract()`](https://github.com/near/nearcore/blob/8fc7bac3b27450b424b5e811de9eed8e628894af/integration-tests/src/tests/runtime/test_evil_contracts.rs#L18-L39).
4. Make a transaction which calls the test contract's `sanity_check()` function. This yields a `FinalExecutionOutcomeView` with `transaction_outcome` and `receipts_outcome`.
5. Compare the `gas_profile`s of these outcomes to the expected gas profiles, using different sets of expectations for stable and nightly protocol.

**Comment by mina86** [comment]
It seems like `WASM_INSTRUCTION` needs to be ignored as well? I’m
getting

```
receipts_gas_profile
────────────┬────────────────────────────────────────────────
  226   226 │         },
  227   227 │         CostGasUsed {
  228   228 │             cost_category: "WASM_HOST_COST",
  229   229 │             cost: "WASM_INSTRUCTION",
  230       │-            gas_used: 24159407184,
        230 │+            gas_used: 28863925992,
  231   231 │         },
  232   232 │         CostGasUsed {
  233   233 │             cost_category: "WASM_HOST_COST",
  234   234 │             cost: "WRITE_MEMORY_BASE",

```

and my guess would be that different environments compile the contract
in different ways which results in not only size of the bytecode being
nondeterministic but also how many instructions are actually executed.

If we want to test WASM_INSTRUCTION cost we might need to prepare
a wasm blob.

**Comment by matklad** [comment]
was fixed by @mooori, thank you!
