### ISSUE TITLE
Profiling wasmer 2 to find bottlenecks in cold start

### ISSUE THREAD

**Issue by ailisp** [near/nearcore#5014]
Current wasmer 2 cold start is still not fast enough, we need to understand what is slow there.

**Comment by nagisa** [comment]
Could you please elaborate what do you mean exactly by “cold start”?

Is it the speed at which the very first contract is prepared since the `neard` process was launched? Or is it the speed at which any given contract gets prepared to run for the first time? Maybe something else?

**Comment by ailisp** [comment]
It's this one:
> Or is it the speed at which any given contract gets prepared to run for the first time? 

Speed of "first contract since neard was launched" isn't important because neard expected to be long running, only restart at  new releases

**Comment by matklad** [comment]
I think we've found some important cases in https://github.com/near/nearcore/issues/7227:

* we are over eager with loading the whole contract from the database to early
* worst-case loading cost (many tiny functions) is very high, in part due to amplification of contract size when going from Webassembly to x86 machine code.
