### ISSUE TITLE
Node should not stuck in state sync loop

### ISSUE THREAD

**Issue by frol** [near/nearcore#5061]
**Describe the bug**

Booting a node (RPC one, but I believe that is not essential here) from a backup pulls in headers and state, and then downloads more headers and stuck at state sync (same last log line produced for hours):

![image](https://user-images.githubusercontent.com/304265/138356351-8f29f53b-ab05-495e-8e25-55daad31cb30.png)

**Expected behavior**

It should boot, sync, and keep the node running fast and smooth.

**Version (please complete the following information):**
- nearcore commit/branch b34c2885532049dad6ea0a954554131fb432985d (includes the hotfix #5058)
- testnet

**Comment by mzhangmzz** [comment]
@EgorKulikov could you take a look as well? Seems that the node is running state sync for four shards and for some reason restart the work over and over again

**Comment by mzhangmzz** [comment]
I think I know what trigged the bug, but I don't know how to fix it quickly since I'm not too familiar with this part of the code. 

I think what happens is that the node is running state sync, and state sync actually completed and it enters `BodySync`, https://github.com/near/nearcore/blob/master/chain/client/src/client_actor.rs#L1475. We know that because in the log, it says `Downloading blocks...`.

Then because `sync` is called periodically, header sync is run again because `SyncStatus` is `BodySync` now (https://github.com/near/nearcore/blob/master/chain/client/src/client_actor.rs#L1347 and https://github.com/near/nearcore/blob/master/chain/client/src/sync.rs#L185)

**Comment by frol** [comment]
Just for the future reference, the issue was that the partners did not compile the node (indexer) with `--release` flag
