### ISSUE TITLE
Avoid memory allocations in networking code

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5206]
We have data structured indexed by `(PeerId, PeerId)` in networking code. Can we somehow avoid doing memory allocations?

```
pub struct RoutingTableActor {
    /// Data structure with all edges. It's guaranteed that `peer.0` < `peer.1`.
    pub edges_info: HashMap<(PeerId, PeerId), Edge>,
    //...
}

    // from chain/network/src/routing/routing_table_actor.rs: 355

    pub fn get_edge(&self, peer0: PeerId, peer1: PeerId) -> Option<Edge> {
        let key = Edge::key(peer0, peer1);
        self.edges_info.get(&key).cloned()
    }

impl Edge {
    pub fn get_pair(&self) -> (PeerId, PeerId) {
        (self.peer0.clone(), self.peer1.clone())
    }
}

```

@matklad Any ideas?

**Comment by pmnoxx** [comment]
@matklad For example: https://github.com/near/nearcore/pull/5209/files

**Comment by pmnoxx** [comment]
For example, we could change `key` in `Edge` to be `Arc<(PeerId, PeerId)>`. That way we could avoid copy when using this in
`HashMap<(PeerId, PeerId), Edge>`

**Comment by matklad** [comment]
Yeah, I think I actually suggesting something along these lines in one of the code reviews. 

The general pattern here is that we want to store a hash-map with objects, where the key is a part of the object itself (which is a pretty common patteren). The way to achieve this in Rust is somewhat counter-intuitive -- rather than using a map, you want to use a set, and rely on a Borrow trait. Here's a small example modeling what we have in near: 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2fd0a4c6dba66a331565683971a39a22

**Comment by pmnoxx** [comment]
@matklad Before we do that, it would make sense first to replace `Edge` with `Arc<Edge>`, and do the same for `PeerId`.

After we do that I'll write a benchmark to see if that's worth it or not.

It may also be a good idea if we could someone create a version of PeerId, that stores inside a precomputed 4 bytes hash. We have to compute a hash for each lookup while doing .get() on
`edges_info: HashSet<(PeerId, PeerId), Edge>`.

Instead of using integers as indexes. We could optimize lookups by `PeerId` by storing a precomputed hash, which would be different on each machine.
```
type PeerId = Arc<Hashed<PeerIdInner>>`
struct Hashed<T> {
   u32: hash,
   inner: T
}
```
