### ISSUE TITLE
Add performance degradation tests

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5214]
@matklad We would like to be able to add performance degradation tests within `#[cfg(test)]`.

Could you provide as an example on how to do it? You mentioned previously that it's better to have benchmarks there, rather than in `benches` folder.

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near

**Comment by matklad** [comment]
I don't have a lot of experience with writing performance degradation *tests* in significant capacity, which literally fail CI if performance is not great. I think couple of times I tried to do that the result was  that the measurements were too noisy to really gate the PR. 

I think what is more usually done is having a performance dashboard which, for each commit in the repository, displays results of the benchmark. Such over time view doesn't suffer a lot from outliers, but still allows you to notice when things drift in an unreasonable direction. See https://perf.rust-lang.org or https://rust-analyzer.github.io/metrics/ for some examples.

I don't know of a simple way to just *have* such a dashboard, for both rust-analyzer and rust it's some custom hand-written code. For rust-analyzer, we run benchmarks during CI, commit there results to a separate github repo (ie, using Git/GitHub as a poor man's cloud database), and then display them client side using some javascript plotting library. Perhaps there exist some more out of the box solutions here. 

As for writing the tests themselves, I think two patterns are useful:

* for integrated benchmarks, the benchmark runs the literal binary (neard) as an external process, hammers it with data, parses the log output and processes it into a benchmark results. 
* for more targeted unit-test benchmark, I've come to use the following pattern: 

```
#[test]
fn benchmark_foo() {
    if std::env::var("RUN_BENCHMARKS").is_err() { return }
    let t = std::time::Instant::now();
    benchmark_code();
    eprintln!("{:?}", t)
}
```

That is, rather than using built-in `#[bench]`, I just abuse the tests. There are several reasons for that:

* benchmarks are not compiled when you run `cargo test`, that means that fixing compilation errors in them after refactors are annoying
* the literal `#[bench]` is unstable
* there are stable replacements like "criterion", but I personally find that they create more problems than they solve. This is somewhat unorthodox opinion, so I don't have a great deal of confidence here, but basically most benchmarking frameworks implement a lot of fancy statistics, graphs and what not, and I didn't find that actually useful to improve performance of software. For all my work so far, perf optimizations was driven by naked eye visible changes measured with `/usr/bin/time` for cases where things get 2x faster. I haven't see the cases where you needed fancy statistics to observe significant improvement among the noise. 


I guess my suggestion for next steps would be:

* specify what *exactly* we want to benchmark, as the first case
* decide where we want to pursue "make the test fail if it is slow" or "display perf dashboard" approach
* implement

**Comment by pmnoxx** [comment]
@matklad

It really depends on what we want to use benchmarks for, we have a few choices:
- one time code optimization - to see whenever rewriting code makes sense - like for example with replacing `Edge` with `Arc<Edge>`. Or when we improve performance of computing routing table by a factor of 1000x, by replacing edges with integers, and other optimizations
For that use case, it would be great to create a few performance tests, and run them them before doing optimization, and after.
It would be nice to run `cargo bench` in CI, to make sure that the code still compiles, but that's not a strict requirement.

- for long term performance degradation tesing 
Ideally, we would make graphs like `https://perf.rust-lang.org/` to manually monitor whenever code became slower over time. 
However, that's not something I'm really interested in doing.

- doing code optimizations from time to time manually
It would be nice to be able to run a series of benchmarks using `cargo bench`, one before doing code optimization, one after and seeing whenever we make some difference.
I guess, it's fine to have code in `benches`. Even if something breaks, it's not really a big deal.


Anyway, I think that I'll keep adding benchmarks to `/benches` folder for now. It's probably not the right time to add automatic tools that run every time we push at the moment.
