### ISSUE TITLE
what is the difference between `IndexerExecutionOutcomeWithReceipt` and `IndexerTransactionWithOutcome`?

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/nearcore#5431]
I've read everything here https://nomicon.io/RuntimeSpec/Transactions.html still don't know the difference?

It is easier to ask the question than setup local node and send transactions inspecting logs.

**Comment by bowenwang1996** [comment]
@frol @khorolets

**Comment by khorolets** [comment]
These are helper structures for indexer. They hold the corresponding pieces of information according to the structure name. 

One holds Transaction and the ExecutionOutcome for that Transaction. 

The other one holds Receipt and the ExecutionOutcome for it. 

They were created to simplify indexing process for an "end user"

Otherwise a developer would need to get those entities from different fields of StreamerMessage and match Transactions/Receipts with corresponding ExecutionOutcomes manually.
