### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by volovyk-s** [near/nearcore#5460]
**Describe the bug**
Localhost is resolved to an ipv6 address but the node is only listening on ipv4 addresses.

**To Reproduce**
Steps described in this issue: https://github.com/near/near-cli/issues/881

**Expected behavior**
Nodes should also listen on ipv6 addresses, such as :: in addition to 0.0.0.0.

**Additional context**
Originally reported and suggested by @nikurt in https://github.com/near/near-cli/issues/881

**Comment by nikurt** [comment]
@marcelo-gonzalez would you be interested in enabling the server on ipv6 addresses? That seems to be a rather easy fix.

**Comment by marcelo-gonzalez** [comment]
hmm, so the problem in near/near-cli#881 I guess happens because the default config.json contains a hard-coded IPv4 addr (`"addr": "0.0.0.0:3030"`) rather than `"addr": "localhost:3030"`. So the default config only happens to match up with localhost on OSes where localhost resolves to IPv4.

Is the right fix to add an IPv6 port for everyone? Somehow to me it feels more natural to only listen on one port by default (localhost). Then the fix would be to change the default config to say "localhost:3030", but since that would possibly be breaking, maybe the next best thing is to do:

```
if "localhost" == "::1" {
  listen_on_ipv6()
}
```

@nikurt @volovyk-s thoughts?

**Comment by volovyk-s** [comment]
@marcelo-gonzalez we are using `localhost`, not `0.0.0.0:3030`  in `NEAR CLI`:
https://github.com/near/near-cli/blob/69319062495bc23fceb9a2276f7e6f209fa28887/config.js#L51
Can you please elaborate?

**Comment by marcelo-gonzalez** [comment]
@volovyk-s right, but nearcore uses `0.0.0.0:3030` in the default config.json, so that it will listen on all available IPv4 addrs.
https://github.com/near/nearcore/blob/ba021dfe96fbeb1fc10b672d2fe59db2fcb1bc98/chain/jsonrpc/src/lib.rs#L78

then that doesn't match up with NEAR CLI using localhost on some OSes I guess

**Comment by volovyk-s** [comment]
@marcelo-gonzalez got it. So, if it's hardcoded in `nearcore`, maybe we should hardcode it to `0.0.0.0:3030` in `NEAR CLI` too?
Sound like a breaking change too. Not sure if there are any other downsides.

**Comment by marcelo-gonzalez** [comment]
yeah if that's actually the problem then maybe that would fix it. Although I'm looking at it again now and I'm not so sure if what I said above is right... The command `curl http://localhost:3030/status` seemed to work just fine in the video in the first comment in https://github.com/near/near-cli/issues/881, so something else is going on.

But in any case I think the fact that `curl http://localhost:3030/status` works but `near-cli` gives `ECONNREFUSED ::1:3030` while also connecting to `localhost` shows that there's something to fix in `near-cli`, not in `nearcore`. @volovyk-s do you think that makes sense? I'll close this issue for now but feel free to reopen if it turns out it really is somethign that should be changed in `nearcore`
