### ISSUE TITLE
Improve error handling at near and use `anyhow::Result`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5695]
Currently, by default we use `.unwrap()`, `.expect()` in many places in our code base.

That has a few issues:
- this cause panic, and output is often unreadable. For example `TcpListener::bind` will say, that a crash happened, will print 50-100 lines of errors, and never even print the port that was open
- code related to handles panics causes causes generated binaries to be bigger
- output is hard to read, to understand what is going on. Rather than printing 50-100 lines of unreadable code we could make panics, print out like this:
```
- main failed
- start with config failed while creating actor
- `PeerManager` actor failed on `::new`
- `TcpListener::bind` failed to bind on port 12345
```

Usage of  `std::Result` , is a bit problematic in the code, every library uses it's own types of errors, which makes it not worth using.

A good alternative like `anyhow::Result` exists, we tried using it with indexer with good results. See https://github.com/near/nearcore/pull/5353

Although, adding error handling to `indexer` is not finished by any means, it's a good step forwards:

May be worth reading https://nick.groenen.me/posts/rust-error-handling/

Open questsions:
- consider `anyhow` or  `thiserror` https://nick.groenen.me/posts/rust-error-handling/

List of PRs done so far:
- https://github.com/near/nearcore/pull/5353
- https://github.com/near/nearcore/pull/5705

**Comment by matklad** [comment]
I think this has to be more nuanced than "use anyhow" or "use thiserror". near is big, there are different contexts, and they require different solutions. 

Some contexts I am aware of:

* CLI interfaces like state viewer, or top-level neard. Here, we should use `anyhow!` to give a nice error messages when trying to read config, genesis, etc. 
* tests -- here we should just panic, but panic with an explicit error message. So, `.expect` or `.unwrap_or_else(|| panic)` rather than plain `.unwrap`, and use `assert_eq!(lhs, rhs, "explanatory message")` rather than `assert_eq!(lhs, rhs)`. Although it's also ok to add messages lazily -- you start with `.unwrap()`, but the first time you need to debug the failure, you go and add a messsage. 
* "expected" errors like invalid transactions or whatnot -- these are ultimatelly reported via json RPC API. Here, we don't really need `std::error::Error` trait at all -- we should just propagate raw enums which describe the error as precisely as possible to the RPC layer, such that we can convert them to JSON which we give backwrads compatability guarantees over. 
* unexpected operational error, like database just crashing from underneath us or stuff like that. Here, it's usually to propagate an error to the caller to deal with. The problem is that the current architecture is based on actors, and actors don't have a caller. If an actor fails, there's nobody specific the failure can be reported to. Here, the right thing is to do whatever the actor library suggest to do with errors, but, rather unexpectedly, actix docs do not tell anything about error handling, so we need to figure that out ourselves.

**Comment by bowenwang1996** [comment]
Agree with what @matklad said. Some panics inside nearcore are intentional: when a node encounters certain undefined behaviors, it is better for it to shut down rather than keep running to avoid permanently getting into an inconsistent state that it is unable to recover from without a ton of manual intervention (completely replacing database for example).

**Comment by pmnoxx** [comment]
> * CLI interfaces like state viewer, or top-level neard. Here, we should use `anyhow!` to give a nice error messages when trying to read config, genesis, etc.

Yes, I agree.The main reason why I started using it was for configs, like `NetworkConfig`. See https://github.com/near/nearcore/pull/5705

> * tests -- here we should just panic, but panic with an explicit error message. So, `.expect(msg)` or `.unwrap_or_else(|| panic!(msg))` rather than plain `.unwrap`, and use `assert_eq!(lhs, rhs, "explanatory message")` rather than `assert_eq!(lhs, rhs)`. Although it's also ok to add messages lazily -- you start with `.unwrap()`, but the first time you need to debug the failure, you go and add a messsage.

Yes, I didn't realize that returning in a test doesn't cause panic. Doing panic, is the right fight to do. The main thing that I want to improve is to make the `panic` more readable. Often we don't see good output, context, when someone calls `.unwrap()` in our code, or `expect()`. It often takes me a bit of time, to modify the code, run test again, to see what the state of values was in case of `.unwrap()`. 

`assert_eq!(a, b, "message v1{}", value)` is nice, because then I can see what is the state of variables, that caused issued.

> * "expected" errors like invalid transactions or whatnot -- these are ultimatelly reported via json RPC API. Here, we don't really need `std::error::Error` trait at all -- we should just propagate raw enums which describe the error as precisely as possible to the RPC layer, such that we can convert them to JSON which we give backwrads compatability guarantees over.

Yes, I'm not saying that `anyhow::Result` solves all issues. It provides useful output that can be used for debugging.
I had experience with working on RPC server, one even writing one myself, what I found really useful was sending a properly formatted output in case of an error.

Bad example: "Response timeout DUE to error"

Good reply:
```
JsonRPC -> 
PeerManagerActor -> 
RoutingTableActor -> 
Found Invalid "peer", "inside `GetPeerInfo` struct
```

`anyhow::Result` provides a simple interface, that's better than just crashing a node, it's not perfect, structured errors would have been better, but it's a good step forward, towards handling properly errors.

I would do it like this, each PR, makes it better:
- PR1: Add proper handling of .unwrap() to print the situation
- PR2: Propagate errors with `Anyhow::Result` - now we get good stack traces
- PR3: Switch to using structured errors, when needed.

> * unexpected operational error, like database just crashing from underneath us or stuff like that. Here, it's usually to propagate an error to the caller to deal with. The problem is that the current architecture is based on actors, and actors don't have a caller. If an actor fails, there's nobody specific the failure can be reported to. Here, the right thing is to do whatever the actor library suggest to do with errors, but, rather unexpectedly, actix docs do not tell anything about error handling, so we need to figure that out ourselves.

`Actix` introduces an `Actor` system, where actor implement `Handler<MessageType>`.
So, every request made, can be tracked down to a source.
There are two cases:
1) A message was sent from outside through our network protocol
2) Though jsonrpc
3) A trigger ran

For example, In our system, we see errors, like `RouteBackNotFound` found, that we want to investigate.
This happens inside `Handler<PeerManagerActor>`. What we can do is, whenever we see that issue, send a reply in `Actix` back to the original sender which was in `ClientActor`. That sender will attach the context, print the state, that what happened, why we send a message to `PeerManagerActor`, before error happened.

`ClientActor` can then send the reply, back to it's caller, then reply to it's caller, and so on. Eventually, we will reach the source of the original message, that cause the chain of messages, leading to the error. 

Instead of seeing single meaning less "RouteBackNotFound". We will be track down to the original message, that caused the issue.  

Ideally while debugging `RouteBackNotFound`, I would like to see a stack of messages, across multiple actors, that were send up to the initial message. That can be done at low cost, there is no reason not to do it.

**Comment by pmnoxx** [comment]
> Agree with what @matklad said. Some panics inside nearcore are intentional: when a node encounters certain undefined behaviors, it is better for it to shut down rather than keep running to avoid permanently getting into an inconsistent state that it is unable to recover from without a ton of manual intervention (completely replacing database for example).

Yes, no one is denying that `panics!` are useful.  We are not talking here, about changing the behavior, and avoiding panics.
I think we should shut down the node as we did before.

However, my main goal here is to improve the output of panics, making them more useful for fixing the issue. If a `panic!` happens, we should print the output in more readable way, and also dump the state of all important variables, that can help us pinpoint he issue. Lack of good `panic!` traces is already, taxing us heavily, it takes extra time and effort to fix the unit tests.
We have a lot of random test failures, that haven't been fixed for a while, and a lot of other issues related to that as well.
Please read my explanation above.
