### ISSUE TITLE
database corruption

### ISSUE THREAD

**Issue by sdmurphy** [near/nearcore#5975]
Bowen asked me to create this issue. However I already wiped the data directory and downloaded a snapshot.

My testnet node got kicked and I saw this in the logs.
![image](https://user-images.githubusercontent.com/8061249/147375978-dcb23da4-408c-4f04-afa9-912ee905bd1a.png)

After restart it looked like this:
![image](https://user-images.githubusercontent.com/8061249/147376317-d89bd45b-9178-4323-8705-e03dac8e014c.png)

MD5SUM of the block:
near@near-testnet-2:~$ md5sum /home/neard/.near/testnet/data/159644.sst
40860d256a7a6327bbe13b19dfb100a3  /home/neard/.near/testnet/data/159644.sst

**Comment by zouyuxuan** [comment]
I unzipped the test network snapshot without 159644.sst and my snapshot size is 153g

**Comment by sdmurphy** [comment]
I did the MD5SUM because I was going to compare it to another node, but it didn't have the 159644.sst either. This node was probably synced from scratch.

**Comment by bowenwang1996** [comment]
@sdmurphy just to confirm, did you happen right after you start the node or after your node has been running for a while? If it is the former there may be an issue with the snapshot.

**Comment by Al3c5** [comment]
I have my backup node stuck with this error 

> ./nearcore/target/release/neard -V
> neard (release 1.23.0) (build 1.23.0) (protocol 49) (db 30)

I t tried to reset with the 2 last snapshots and it keeps ending up with this error. 
Here is what I did 

> stop neard
> rm -Rf data/*
> replace config.json and genesis.json with the last version 
> extract data.tar last version in data dir (current archive size is 264G, I didn't have yesterday's size but a bit lower)
> start neard 

Then downloading headers always works. 
It either fails: 
- when it comes to download blocks. There is a ~5 min gap in the log, then this error arise
OR
-  after having been able to download a couple of blocks.

Then a restart gives ERROR/WARN about corruption block before the node waits for peers (and stays there with 0/0/40 or 1/1/40)


I don't understand this issue since I could sync another node with the same snap (the 264G one).

**Comment by Al3c5** [comment]
Also, my server is not running out of space and I tried to reset near home on two different NVMe disks. 
It keeps running in this error.

**Comment by bowenwang1996** [comment]
@sdmurphy @Al3c5 please keep a copy of the database if this happens again. Currently we cannot do anything without seeing the database itself.
