### ISSUE TITLE
Add --log-level as a command line option OR config.json file option

### ISSUE THREAD

**Issue by mintiayields** [near/nearcore#6008]
I have seen this discussed as a RUST_LOG environment variable usage, however it will have a lot more sense as a config file option or a command line option. I sometimes get a hundred warnings a second written to my neard logs and there is not much I can do to prevent this. 
I suggest that this is put in config.json and has multiple options, for instance: "log_level = info, error"

**Comment by mina86** [comment]
I’m honestly not convinced this needs to be a flag or config option. The feature is available and adding a flag would just introduce unnecessary code and complicate interaction between RUST_LOG and said flag. Adding config option would make it even more complicated since config file is read at later stage during startup.

**Comment by mintiayields** [comment]
Exporting RUST_LOG variable will not produce any effect in my case. When printenv clearly shows that RUST_LOG is set to error, the log file continues to be filled with numerous warnings and info messages. I wouldn't mind the latter as they show valuable info, but the warnings are mostly junk and inflate the log file like crazy.

**Comment by mina86** [comment]
No, it’s good. Currently waiting for review.
