### ISSUE TITLE
Create DB snapshots without stopping the node

### ISSUE THREAD

**Issue by nikurt** [near/nearcore#6244]
Currently we need to stop a node to make a snapshot of the database.
Using Checkpoints feature of RocksDB it should be possible to instantly snapshot the DB of a running node: http://rocksdb.org/blog/2015/11/10/use-checkpoints-for-efficient-snapshots.html

I don't know how checkpoints interact with ongoing updates of the DB. I guess ongoing updates are not a problem, but can't find a confirmation in the docs.

**Comment by abacabadabacaba** [comment]
Checkpoints work by creating hard links to SST files, which hold the majority of the data. Other files are copied. This is safe because once created, SST files are not modified. Instead, during compaction, new SST files are created and old ones are removed.
The [wiki page](https://github.com/facebook/rocksdb/wiki/Checkpoints) says that checkpoints are consistent snapshots, so ongoing updates shouldn't be a problem.
