### ISSUE TITLE
Consider re-exporting rocksdb crate from store

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6301]
[https://github.com/near/nearcore/pull/6300](https://github.com/near/nearcore/pull/6300) made me realize that we specify version of rocks we use in several places. This is a bit subomtimal. In the `store/lib.rs` we might want to add `pub extern crate rocksdb;` to have the version specified in just one Cargo.toml

**Comment by mina86** [comment]
I don’t know if this is really an issue.  Yes, we need to update the version in three places but that’s hardly a large number.  Indexer uses rocksdb directly because it creates its own database unrelated to store.  runtime-params-estimator uses the crate to bypass all of the abstraction.  It doesn’t feel right to export rocksdb through store just to facilitate easy abstraction layer breaking.
