### ISSUE TITLE
Move Warn for Peer bandwidth exceeded threshold to DEBUG log

### ISSUE THREAD

**Issue by janewang** [near/nearcore#6339]
To avoid spamming the log, let's move this WARN to DEBUG log

<img width="783" alt="Screen Shot 2022-02-22 at 3 24 49 PM" src="https://user-images.githubusercontent.com/734336/155213175-ea8d98c5-d1ca-49e9-9eae-c6e298ec2ffe.png">

Too much `WARN near_network::peer_manager::peer_manager_actor: Peer bandwidth exceeded threshold`:
<img width="1276" alt="Screen Shot 2022-02-23 at 10 21 56 PM" src="https://user-images.githubusercontent.com/734336/155451953-e56b775a-9de3-4e41-8c57-39a92ff07b0e.png">
Please move to DEBUG log.

**Version (please complete the following information):**
- nearecore 1.24.0
- mainnet

**Comment by bowenwang1996** [comment]
@pompon0 could you potentially help with this issue?

**Comment by pompon0** [comment]
sure, on it

**Comment by mina86** [comment]
I’ve brought it up on Zulip a while back and @mm-near mentioned that:

> for the first case (bandwidth exceeded -- we should probably ignore bandwidth limits during syncing - as they will be exceeded for sure). 

So it’s just adding `if !sync_status.is_syncing() { ... }` which isn’t that trivial since PeerManager does not have direct access to `sync_status` and ClientActor doesn’t provide a trivial way of getting it out as far as I can see. But I might be missing something here.
