### ISSUE TITLE
Gas calculation flawed/unclear in Explorer

### ISSUE THREAD

**Issue by trezbouchez** [near/nearcore#6972]
I know there's been a bunch of issues reported on how the Explorer displays its gas figures, namely:
https://github.com/near/nearcore/issues/6352
https://github.com/near/near-explorer/issues/904

However, when writing e2e tests for my contract (workspaces) I encountered a weirdness that goes beyond that.   

Taking a testnet transaction as an example:

5NkhuEsyx9qftLGPZDTYxcKJTAPSchgCoPJJRRtzhBe3

Opening it in the Explorer reveals that the transaction succeeded even though the ATTACHED GAS was 1TGas (correct number) and the function execution alone consumed 3TGas. I realize the ATTACHED GAS number does not include the extra prepaid gas for converting the transaction into a receipt. Still it does not explain why it didn't run out of gas even thought the execution alone consumed 3 times more gas than what was attached.

Some less important (but related) thoughts and suggestions:

1. The explorer should show the exact figures for gas consumption and tokens burnt, not heavily rounded numbers only. As a user I'd expect to be able to check those numbers add up and reconcile them against my account balance.
2. There's one annoying issue with the near-workspaces. When inspecting gas consumption of the function call outcome (`total_gas_burnt`), which is the recommended way of estimating gas required by contract calls, the total includes both the gas require for turning the txn into a receipt and the gas burnt by the refund transfer of the excess (but paid) gas. The former seems to be and extra gas that's always prepaid and added to the attached gas, the latter is a transfer initiated by the system and, as such, not paid by the signer. So it's misleading to include these two in the total (which is the basis for estimation of how much gas needs to be attached to a call)

Hubert Pietrzykowski

**Comment by jakmeier** [comment]
Hi Hubert,

We have to be a bit careful with naming here. What the explorer displays today as "Attached Gas" is not all the gas available to the transaction but only the gas specifically added by the user for smart contract execution. In the other issue, I call this "prepaid gas" as this is what we used in nearcore code. But user-facing documentation seems to use "attached gas" instead, so let's use that.

With that meaning of "attached gas" in mind, attached gas is only used for dynamic gas usage, aka WASM execution and promises created therein. All statically known gas costs (at the time of receipt creation) will be charged directly from the sender account, not from attached gas.

In your example, the _receipt creation_ burns 2.428 Tgas, which the explorer shows as `Convert Transaction To Receipt`. But this is only half the statically known gas cost. The other half is _receipt execution_, which for now happens to be the exact same cost as receipt creation but charged at the receiver instead of at the sender. Therefore, the total _execution_ gas is 3.23Tgas but only (3.23Tgas - 2.428Tgas) = 0.802Tgas is taken from attached gas.

In https://github.com/near/near-explorer/issues/904 I already suggested to change what the explorer shows in one way or another, such that the numbers at least add up. Exactly because it is so confusing today.

Does that resolve your main question?

Regarding the other two points.
1. Note that hovering over burnt tokens gives you the exact token number. Unfortunately, this doesn't work for gas. Feel free to create an issue in the explorer repository with your suggestion.
2. This is indeed a problem for estimating how much gas should be attached. Probably you should create an issue in near-workspaces and see if they have a solution for the discrepancy between `total_gas_burnt` and what you should attach to a function call. But let me also ping @idea404, I remember we discussed how to improve gas estimation for users and maybe he knows a better way already.

**Comment by idea404** [comment]
There is currently no straightforward way to determine gas costs in advance for smart contracts function calls. It has occurred to me there could be a service (through a REST API for instance) that could tell what the costs would be for a given `mainnet` contract call in advance by ["spooning"](https://github.com/near/workspaces-rs#spooning---pulling-existing-state-and-contracts-from-mainnettestnet) the smart contract with state (workspaces feature), running it on testnet, returning the gas profile and deleting the testnet account hosting the spooned smart contract. There's still some digging to do here on my part. 

As for your second point @trezbouchez, perhaps the `.outcomes`  data structure from `TransactionResult` is more like what you're looking for (if you're working with `workspaces-js`)? That should give you such an overview:

```js
[
       {
        executor_id: 'test.near',
        gas_burnt: 2428048448238,
        logs: [],
        metadata: {
            gas_profile: null,
            version: 1,
        },
        receipt_ids: [
            'B9TuvVemsBXeKD3iqavdwXLh4SsbXD7F89w35NQ3Kkgh',
        ],
        status: {
            SuccessReceiptId: 'B9TuvVemsBXeKD3iqavdwXLh4SsbXD7F89w35NQ3Kkgh',
        },
        tokens_burnt: '2428048448238000000000',
    },
    {
        executor_id: 'fungible-token.test.near',
        gas_burnt: 4064850571344,
        logs: [
            'Transfer 100 from test.near to ali.test.near',
        ],
        metadata: {
            gas_profile: Array[…],
            version: 1,
        },
        receipt_ids: [
            'GUbUES4EBepcFcmjMvwVr5CQSU7MzNYjAhaJN3jmRPXj',
        ],
        status: {
            SuccessValue: '',
        },
        tokens_burnt: '4064850571344000000000',
    },
    {
        executor_id: 'test.near',
        gas_burnt: 223182562500,
        logs: [],
        metadata: {
            gas_profile: [],
            version: 1,
        },
        receipt_ids: [],
        status: {
            SuccessValue: '',
        },
        tokens_burnt: '0',
    },
]
```  

Here's a snippet of how I got here in TypeScript: 

```ts
  const ir: TransactionResult = await root.callRaw(
      ft,
      'ft_transfer',
      {
          receiver_id: ali,
          amount: transferAmount,
      },
      { attachedDeposit: '1' },
  );
  t.log("outcomes: ", ir.outcomes);
```

**Comment by trezbouchez** [comment]
> In your example, the _receipt creation_ burns 2.428 Tgas, which the explorer shows as `Convert Transaction To Receipt`. But this is only half the statically known gas cost. The other half is _receipt execution_, which for now happens to be the exact same cost as receipt creation but charged at the receiver instead of at the sender. Therefore, the total _execution_ gas is 3.23Tgas but only (3.23Tgas - 2.428Tgas) = 0.802Tgas is taken from attached gas.
>
> Does that resolve your main question?

Yes, absolutely. This is what I suspected but wasn't quite sure. Maybe I didn't read the documentation from top to bottom. Thanks for your detailed explanation @jakmeier. 

> 1. Note that hovering over burnt tokens gives you the exact token number. Unfortunately, this doesn't work for gas. Feel free to create an issue in the explorer repository with your suggestion.

Yeah, I noticed that hovering shows the tokens burnt but no gas. Will create an issue as suggested.

> 2. This is indeed a problem for estimating how much gas should be attached. Probably you should create an issue in near-workspaces and see if they have a solution for the discrepancy between `total_gas_burnt` and what you should attach to a function call. But let me also ping @idea404, I remember we discussed how to improve gas estimation for users and maybe he knows a better way already.

I should have probably brought this up in the workspaces thread. Sorry for polluting core. Now that the milk is spilled anyway let me elaborate on this problem a little more (and close the issue).
As a contract developer I would like to be able to write robust end-to-end tests that include verification of the signer account balance in scenarios that may include multiple cross-contract calls. This is actually my case (working on an on-chain royalties-bound music NFT marketplace that includes cross-calls for minting, royalties distribution and stuff). Because each of the x-calls can potentially fail there's a certain range of storage and balance outcomes that need to be tested (to make sure all deposits corresponding to freed/aborted storage get returned in every case). To be able to correctly reconcile the resulting account balance vs deposits I need to be able to determine how much tokens were burnt to cover gas costs first. Then the remaining balance difference is deposit-related and can be used to check the correctness of deposit handling. 
So my question was not only motivated by the need of estimating the gas usage (how much gas to attach to attach). I'm actually fine with 'attach more / get refunded' policy. My main problem was that I couldn't tell how much gas was actually paid by the signer (how much of their tokens were burnt as gas). I relied on `total_gas_burnt` which was obviously wrong approach and I realized that after my numbers didn't add up. Inspecting the `outcome` array, as @idea404 suggested (and summing figures from all `tokens_burnt` fields) is how things should be done. Thanks for pointing that out. 
Still, I think it'd be convenient to have a `total_tokens_burnt` field but this is very minor.
Thank you very much for shedding some light on those topics, @jakmeier and @idea404
