### ISSUE TITLE
Header download percentage is incorrect

### ISSUE THREAD

**Issue by DDeAlmeida** [near/nearcore#7202]
**Describe the bug**
The % is completely wrong.

**To Reproduce**
Just start node and wait informations
Example: Downloading headers 82.00% (4758 left; at 1034064)

**Expected behavior**
Good %

**Screenshots**
![image](https://user-images.githubusercontent.com/52310650/179373292-13724fd6-da4d-486b-bbf9-016a13ed40ea.png)

**Version (please complete the following information):**
- nearcore Master / latest commit
- shardnet

**Comment by mina86** [comment]
The percentage is calculated from node’s head rather than as a total number of blocks.  So if your node is at 1012395 (as seen in the first number in status line) and current chain head is at 1038822 than the progress is measured between those two numbers; not between genesis head and current chain head.
