### ISSUE TITLE
Inconsistent min_gas_price value when in localnet/sandbox

### ISSUE THREAD

**Issue by ChaoticTempest** [near/nearcore#7466]
**Describe the bug**
On localnet or a sandbox node, gas estimations are 10x the amount. Seems this happening since `min_gas_price` is set to `1_000_000_000` instead of `100_000_000` which is what is found on mainnet/testnet. From my findings, `BlockEconomicsConfig::min_gas_price` determines the min_gas_price dynamically and lowers the min_gas_price to `100_000_000` for mainnet/testnet since their genesis protocol version is below a threshold. Meanwhile newly launched localnet or sandbox nodes have protocol version of 56 as of the time of writing this issue which doesn't meet the threshold and causes this inconsistency.

**To Reproduce**
- clone `https://github.com/near/workspaces-rs/`
- checkout branch `phuong/test/proxy`
- run `cargo run --example proxy` and then an error should occur like the following:
```
Error: handler error: [An error happened during transaction execution: InvalidAccessKeyError(NotEnoughAllowance { account_id: AccountId("dev-20220823224325-18831006822820"), public_key: ed25519:FzLCgiBnbhUvmcX78YWdugM7oapurcXcjAS4Fwt3hXi7, allowance: 56287890191155200000000, cost: 187424484981165931516950 })]
```
- to test for newer changes once changes are made to nearcore:
  - `cd nearcore`
  - `make sandbox`
  - `cd workspaces-rs`
  - `NEAR_SANDBOX_BIN_PATH=/abolute/path/to/nearcore/sandbox/debug/neard cargo run --example proxy` where the error no longer occurs

**Version (please complete the following information):**
- nearcore master
- local

**Additional context**
Initial conversation on it in zulip:
https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/Inconsistent.20min_gas_price.20on.20localnet.2Fsandbox/near/294942074

**Comment by akhi3030** [comment]
CC: @jakmeier.  Is this something that you can help diagnose please?

**Comment by matklad** [comment]
Code in question: 

https://github.com/near/nearcore/blob/c0706b7780fa7f08d844280821a93033ea8674a6/chain/chain/src/types.rs#L172-L192

I don't understand why *genesis* protocol version (as opposed to block's protocol version) would affect this in any way, this requires some git-blame archaeology.

**Comment by jakmeier** [comment]
I think just increasing the constant really is the best way forward. The default gensis config should produce the gas price that is most recent. But I also added comments to make things easier to understand. See PR #7475.

I also noticed that shardnet has been launched with the old `min_gas_price` value, 10x the gas price used in mainnet/testnet/betanet. I don't think it matters in any way but probably not intentional. cc @mm-near @gmilescu

**Comment by mm-near** [comment]
Ah - that explains why some people have seen transactions costing over 30 NEAR ..

**Comment by jakmeier** [comment]
Well, 30 NEAR still sounds like a bit much for a single transaction, if it was only because of the 10x. But I also noticed in [the explorer](https://explorer.shardnet.near.org/blocks/6wPgWj6Zy5BqNLHf6dwTJcHWQDinTodh4DTRWBLMdSMB) that gas price has been inflated to the max, making it another 20x more expensive. With that, 150Tgas indeed costs 3 NEAR.

**Comment by jakmeier** [comment]
Oh, I just noticed that our pessimistic gas price charges go beyond the cap of 20x minimum price. Filed #7477. That explains why users needed more than 30 NEAR to initiate a transaction.
