### ISSUE TITLE
Mainnet archive node, loses blocks

### ISSUE THREAD

**Issue by ibadullaev-inc4** [near/nearcore#7627]
**Describe the bug**
Hi, Please help me resolve issue.
I have mainnet-archive node, before couple a days ago my node start to lose blocks.

**Screenshots**
![image](https://user-images.githubusercontent.com/101882172/190719460-627aef08-4b8d-481a-918b-7ece1fe40e54.png)
![image](https://user-images.githubusercontent.com/101882172/190721051-a2c9491d-b4da-4402-b900-e90c50931bb5.png)

**Version:**
- hardware 
```
AWS Instance Type: c5.2xlarge
Disk: gp3, IOPS = 12.000 Throutput = 500
```
- docker  -  "nearprotocol/nearcore" 
```
DIGEST:sha256:40840b5fa21a2862bb193a76199dd190d5924a5606f30c79b1a4697b5fcb863f
```
```
root@nearat-0:/# neard -V
neard (release trunk) (build 1.1.0-2792-gc6d565440-modified) (rustc 1.63.0) (protocol 57) (db 31)
```
- mainnet

Node Start Logs:
[mainnet-archive.log](https://github.com/near/nearcore/files/9586974/mainnet-archive.log)

**Comment by mm-near** [comment]
Hey @ibadullaev-inc4 

Last week, we had a couple large launches on mainnet, that drastically increased the average traffic.
We're aware that it hit the archival nodes more than the regular ones (due to the fact, that the storage is far larger on archival nodes, they do require more disk lookups, which does impact latency).

The traffic did drop after Nearcon, so your node should hopefully catchup fast now.

Still - we have a fix for it, that will be rolling out with the next release (1.29) in couple days.

**Comment by ibadullaev-inc4** [comment]
Thanks for response
