### ISSUE TITLE
State Sync: Fix known dumping and catchup issues

### ISSUE THREAD

**Issue by Sarah-NEAR** [near/nearcore#9572]
ix known dumping and catchup issues. Investigate and fix every case of

a shard state not being completely dumped

a test node failing to statesync/catchup

**Comment by nikurt** [comment]
Tested on a couple of dump/sync nodes in both testnet and mainnet.
The process used to work reliably.
Issues observed:
* Failed to drop the existing state before applying state parts - fixed
* Failed to get a state header because backwards compatibility is hard - fixed
* Handling of last block missing a chunk - implemented
