### ISSUE TITLE
`neard-sandbox` built @master from source panics at runtime

### ISSUE THREAD

**Issue by shariffdev** [near/nearcore#9665]
**Describe the bug**
There is a panic at runtime running `neard-sandbox` built from source `@master`. An example is when running the [workspace-rs](https://github.com/near/near-workspaces-rs) tests. The panic does not happen when using the latest nearcore release `branch 1.35.0 https://github.com/near/nearcore`

**To Reproduce**
Build neard-sandbox from source:
```sh
git clone https://github.com/near/nearcore.git
cd nearcore
make sandbox-release
```

Run workspase-rs tests locally:

```sh
git clone https://github.com/near/near-workspaces-rs.git
cd near-workspaces-rs
NEAR_SANDBOX_BIN_PATH="/path/to/built/neard-sandbox" NEAR_RPC_TIMEOUT_SECS=100 cargo test --verbose --features unstable
```

**Expected behavior**
Tests should run normally as in `@1.35.0`

**Screenshots**
<img width="1450" alt="Screenshot 2023-10-11 at 09 21 58" src="https://github.com/near/nearcore/assets/141004977/ea9c838d-156e-4e93-bd8e-2887ab9e7d3b">

**Version (please complete the following information):**
- nearcore: `@master #3a56da2b76b280f7e0c42d4b4d3242b519908201`
- rust version: `rustc 1.73.0 (cc66ad468 2023-10-03)`
- feature(s): `sandbox`
- system: `macOS`

**Additional Context**
I've played around with toggling `sandbox` and `near_vm` features and not found a simple fix. But I could be wrong.

**Comment by frol** [comment]
@shariffdev I can reproduce it on my side with the commit you referenced, but after that there was PR #9658 that stabilized the restriction for creation of top-level accounts, and so top-level accounts (dev-xxxxxx-xxxxx) cannot be created anymore without registrar, so this issue is masked. Please, adjust near-workspaces-rs to either (1) use the root account to create sub-accounts as dev accounts (instead of `dev-xxxxx-xxxxx`, create `dev-xxxxx-xxxxx.sandnet` or whatever we use for the root account id there); OR (2) use registrar account to continue creating `dev-xxxxx-xxxxx` accounts - whichever path will be faster to hack, so we can test and reproduce the issue.

**Comment by shariffdev** [comment]
@frol thanks for the strategies. I was able to recreate the issue still. Heres the workaround: https://github.com/shariffdev/workspaces-rs/tree/hack/tla-acc-id

**Comment by shariffdev** [comment]
I could not find the "registrar" account info, there was the `validator_key` and the `node_key` when initialising sandbox. Is it stored somewhere accessible?

**Comment by bowenwang1996** [comment]
@frol on the topic of top-level accounts, could workspace adjust the config in the local environment that it spins up? #9658 changes only the config value (32 -> 63).
